//package com.techstomach.ehs.core;
//
//import java.io.Serializable;
//import java.util.Collections;
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Map;
//import java.util.Set;
//import java.util.WeakHashMap;
//import javax.persistence.Basic;
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_appointment.
// * @author autogenerated
// */
//
//@Entity
//@Table(name = "jd_appointment", catalog = "jdehs_dev")
//public class JdAppointment implements Cloneable, Serializable{
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033268L;
//
//	/** Use a WeakHashMap so entries will be garbage collected once all entities
//		referring to a saved hash are garbage collected themselves. */
//	private static final Map<Serializable, Long> SAVED_HASHES =
//		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
//
//	/** hashCode temporary storage. */
//	private volatile Long hashCode;
//
//
//	/** Field mapping. */
//	private String appointmentdescription;
//	/** Field mapping. */
//	private Integer appointmentstatus;
//	/** Field mapping. */
//	private String appointmenttakenby;
//	/** Field mapping. */
//	private Date appoitmentstarttime;
//	/** Field mapping. */
//	private JdClinic clinicidFk;
//	/** Field mapping. */
//	private Date creationdate;
//	/** Field mapping. */
//	private Long id = 0L; // init for hibernate bug workaround
//	/** Field mapping. */
//	private Long invoiceidFk;
//	/** Field mapping. */
//	private Set<JdDiagnosticChart> jdDiagnosticCharts = new HashSet<JdDiagnosticChart>();
//
//	/** Field mapping. */
//	private Set<JdInvoice> jdInvoices = new HashSet<JdInvoice>();
//
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Date modifieddate;
//	/** Field mapping. */
//	private Integer slotduration;
//	/** Field mapping. */
//	private Date slotendtime;
//	/** Field mapping. */
//	private Date slotstarttime;
//	/** Field mapping. */
//	private Date usercheckin;
//	/** Field mapping. */
//	private Date usercheckout;
//	/** Field mapping. */
//	private JdUser useridFk;
//	/**
//	 * Default constructor, mainly for hibernate use.
//	 */
//	public JdAppointment() {
//		// Default constructor
//	}
//
//	/** Constructor taking a given ID.
//	 * @param id to set
//	 */
//	public JdAppointment(Long id) {
//		this.id = id;
//	}
//
//	/** Constructor taking a given ID.
//	 * @param appointmentstatus Integer object;
//	 * @param appoitmentstarttime Date object;
//	 * @param clinicidFk JdClinic object;
//	 * @param id Long object;
//	 * @param modifiedby String object;
//	 * @param slotduration Integer object;
//	 * @param slotendtime Date object;
//	 * @param slotstarttime Date object;
//	 * @param usercheckin Date object;
//	 * @param usercheckout Date object;
//	 * @param useridFk JdUser object;
//	 */
//	public JdAppointment(Integer appointmentstatus, Date appoitmentstarttime, JdClinic clinicidFk,
//			Long id, String modifiedby, Integer slotduration,
//			Date slotendtime, Date slotstarttime, Date usercheckin,
//			Date usercheckout, JdUser useridFk) {
//
//		this.appointmentstatus = appointmentstatus;
//		this.appoitmentstarttime = appoitmentstarttime;
//		this.clinicidFk = clinicidFk;
//		this.id = id;
//		this.modifiedby = modifiedby;
//		this.slotduration = slotduration;
//		this.slotendtime = slotendtime;
//		this.slotstarttime = slotstarttime;
//		this.usercheckin = usercheckin;
//		this.usercheckout = usercheckout;
//		this.useridFk = useridFk;
//	}
//
//
//
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Transient
//	public Class<?> getClassType() {
//		return JdAppointment.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: appointmentdescription.
//	 * @return A String object (this.appointmentdescription)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getAppointmentdescription() {
//		return this.appointmentdescription;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: appointmentdescription.
//	 * @param appointmentdescription the appointmentdescription value you wish to set
//	 */
//	public void setAppointmentdescription(final String appointmentdescription) {
//		this.appointmentdescription = appointmentdescription;
//	}
//
//    /**
//     * Return the value associated with the column: appointmentstatus.
//	 * @return A Integer object (this.appointmentstatus)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Integer getAppointmentstatus() {
//		return this.appointmentstatus;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: appointmentstatus.
//	 * @param appointmentstatus the appointmentstatus value you wish to set
//	 */
//	public void setAppointmentstatus(final Integer appointmentstatus) {
//		this.appointmentstatus = appointmentstatus;
//	}
//
//    /**
//     * Return the value associated with the column: appointmenttakenby.
//	 * @return A String object (this.appointmenttakenby)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getAppointmenttakenby() {
//		return this.appointmenttakenby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: appointmenttakenby.
//	 * @param appointmenttakenby the appointmenttakenby value you wish to set
//	 */
//	public void setAppointmenttakenby(final String appointmenttakenby) {
//		this.appointmenttakenby = appointmenttakenby;
//	}
//
//    /**
//     * Return the value associated with the column: appoitmentstarttime.
//	 * @return A Date object (this.appoitmentstarttime)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getAppoitmentstarttime() {
//		return this.appoitmentstarttime;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: appoitmentstarttime.
//	 * @param appoitmentstarttime the appoitmentstarttime value you wish to set
//	 */
//	public void setAppoitmentstarttime(final Date appoitmentstarttime) {
//		this.appoitmentstarttime = appoitmentstarttime;
//	}
//
//    /**
//     * Return the value associated with the column: clinicidFk.
//	 * @return A JdClinic object (this.clinicidFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "clinicId_fk", nullable = false )
//	public JdClinic getClinicidFk() {
//		return this.clinicidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: clinicidFk.
//	 * @param clinicidFk the clinicidFk value you wish to set
//	 */
//	public void setClinicidFk(final JdClinic clinicidFk) {
//		this.clinicidFk = clinicidFk;
//	}
//
//    /**
//     * Return the value associated with the column: creationdate.
//	 * @return A Date object (this.creationdate)
//	 */
//	public Date getCreationdate() {
//		return this.creationdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: creationdate.
//	 * @param creationdate the creationdate value you wish to set
//	 */
//	public void setCreationdate(final Date creationdate) {
//		this.creationdate = creationdate;
//	}
//
//    /**
//     * Return the value associated with the column: id.
//	 * @return A Long object (this.id)
//	 */
//    @Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Basic( optional = false )
//	@Column( name = "appointmentid", nullable = false  )
//	public Long getId() {
//		return this.id;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: id.
//	 * @param id the id value you wish to set
//	 */
//	public void setId(final Long id) {
//		// If we've just been persisted and hashCode has been
//		// returned then make sure other entities with this
//		// ID return the already returned hash code
//		if ( (this.id == null || this.id == 0L) &&
//				(id != null) &&
//				(this.hashCode != null) ) {
//		SAVED_HASHES.put( id, this.hashCode );
//		}
//		this.id = id;
//	}
//
//    /**
//     * Return the value associated with the column: invoiceidFk.
//	 * @return A Long object (this.invoiceidFk)
//	 */
//	@Basic( optional = true )
//	@Column( name = "invoiceid_fk"  )
//	public Long getInvoiceidFk() {
//		return this.invoiceidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: invoiceidFk.
//	 * @param invoiceidFk the invoiceidFk value you wish to set
//	 */
//	public void setInvoiceidFk(final Long invoiceidFk) {
//		this.invoiceidFk = invoiceidFk;
//	}
//
//    /**
//     * Return the value associated with the column: jdDiagnosticChart.
//	 * @return A Set&lt;JdDiagnosticChart&gt; object (this.jdDiagnosticChart)
//	 */
// 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "appointmentidFk"  )
// 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Set<JdDiagnosticChart> getJdDiagnosticCharts() {
//		return this.jdDiagnosticCharts;
//
//	}
//
//	/**
//	 * Adds a bi-directional link of type JdDiagnosticChart to the jdDiagnosticCharts set.
//	 * @param jdDiagnosticChart item to add
//	 */
//	public void addJdDiagnosticChart(JdDiagnosticChart jdDiagnosticChart) {
//		jdDiagnosticChart.setAppointmentidFk(this);
//		this.jdDiagnosticCharts.add(jdDiagnosticChart);
//	}
//
//
//    /**
//     * Set the value related to the column: jdDiagnosticChart.
//	 * @param jdDiagnosticChart the jdDiagnosticChart value you wish to set
//	 */
//	public void setJdDiagnosticCharts(final Set<JdDiagnosticChart> jdDiagnosticChart) {
//		this.jdDiagnosticCharts = jdDiagnosticChart;
//	}
//
//    /**
//     * Return the value associated with the column: jdInvoice.
//	 * @return A Set&lt;JdInvoice&gt; object (this.jdInvoice)
//	 */
// 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "appointmentidFk"  )
// 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Set<JdInvoice> getJdInvoices() {
//		return this.jdInvoices;
//
//	}
//
//	/**
//	 * Adds a bi-directional link of type JdInvoice to the jdInvoices set.
//	 * @param jdInvoice item to add
//	 */
//	public void addJdInvoice(JdInvoice jdInvoice) {
//		jdInvoice.setAppointmentidFk(this);
//		this.jdInvoices.add(jdInvoice);
//	}
//
//
//    /**
//     * Set the value related to the column: jdInvoice.
//	 * @param jdInvoice the jdInvoice value you wish to set
//	 */
//	public void setJdInvoices(final Set<JdInvoice> jdInvoice) {
//		this.jdInvoices = jdInvoice;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: modifieddate.
//	 * @return A Date object (this.modifieddate)
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifieddate.
//	 * @param modifieddate the modifieddate value you wish to set
//	 */
//	public void setModifieddate(final Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//    /**
//     * Return the value associated with the column: slotduration.
//	 * @return A Integer object (this.slotduration)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Integer getSlotduration() {
//		return this.slotduration;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: slotduration.
//	 * @param slotduration the slotduration value you wish to set
//	 */
//	public void setSlotduration(final Integer slotduration) {
//		this.slotduration = slotduration;
//	}
//
//    /**
//     * Return the value associated with the column: slotendtime.
//	 * @return A Date object (this.slotendtime)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getSlotendtime() {
//		return this.slotendtime;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: slotendtime.
//	 * @param slotendtime the slotendtime value you wish to set
//	 */
//	public void setSlotendtime(final Date slotendtime) {
//		this.slotendtime = slotendtime;
//	}
//
//    /**
//     * Return the value associated with the column: slotstarttime.
//	 * @return A Date object (this.slotstarttime)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getSlotstarttime() {
//		return this.slotstarttime;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: slotstarttime.
//	 * @param slotstarttime the slotstarttime value you wish to set
//	 */
//	public void setSlotstarttime(final Date slotstarttime) {
//		this.slotstarttime = slotstarttime;
//	}
//
//    /**
//     * Return the value associated with the column: usercheckin.
//	 * @return A Date object (this.usercheckin)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getUsercheckin() {
//		return this.usercheckin;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: usercheckin.
//	 * @param usercheckin the usercheckin value you wish to set
//	 */
//	public void setUsercheckin(final Date usercheckin) {
//		this.usercheckin = usercheckin;
//	}
//
//    /**
//     * Return the value associated with the column: usercheckout.
//	 * @return A Date object (this.usercheckout)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getUsercheckout() {
//		return this.usercheckout;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: usercheckout.
//	 * @param usercheckout the usercheckout value you wish to set
//	 */
//	public void setUsercheckout(final Date usercheckout) {
//		this.usercheckout = usercheckout;
//	}
//
//    /**
//     * Return the value associated with the column: useridFk.
//	 * @return A JdUser object (this.useridFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "userId_fk", nullable = false )
//	public JdUser getUseridFk() {
//		return this.useridFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: useridFk.
//	 * @param useridFk the useridFk value you wish to set
//	 */
//	public void setUseridFk(final JdUser useridFk) {
//		this.useridFk = useridFk;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdAppointment clone() throws CloneNotSupportedException {
//
//        final JdAppointment copy = (JdAppointment)super.clone();
//
//		copy.setAppointmentdescription(this.getAppointmentdescription());
//		copy.setAppointmentstatus(this.getAppointmentstatus());
//		copy.setAppointmenttakenby(this.getAppointmenttakenby());
//		copy.setAppoitmentstarttime(this.getAppoitmentstarttime());
//		copy.setClinicidFk(this.getClinicidFk());
//		copy.setCreationdate(this.getCreationdate());
//		copy.setId(this.getId());
//		copy.setInvoiceidFk(this.getInvoiceidFk());
//		if (this.getJdDiagnosticCharts() != null) {
//			copy.getJdDiagnosticCharts().addAll(this.getJdDiagnosticCharts());
//		}
//		if (this.getJdInvoices() != null) {
//			copy.getJdInvoices().addAll(this.getJdInvoices());
//		}
//		copy.setModifiedby(this.getModifiedby());
//		copy.setModifieddate(this.getModifieddate());
//		copy.setSlotduration(this.getSlotduration());
//		copy.setSlotendtime(this.getSlotendtime());
//		copy.setSlotstarttime(this.getSlotstarttime());
//		copy.setUsercheckin(this.getUsercheckin());
//		copy.setUsercheckout(this.getUsercheckout());
//		copy.setUseridFk(this.getUseridFk());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("appointmentdescription: " + this.getAppointmentdescription() + ", ");
//		sb.append("appointmentstatus: " + this.getAppointmentstatus() + ", ");
//		sb.append("appointmenttakenby: " + this.getAppointmenttakenby() + ", ");
//		sb.append("appoitmentstarttime: " + this.getAppoitmentstarttime() + ", ");
//		sb.append("creationdate: " + this.getCreationdate() + ", ");
//		sb.append("id: " + this.getId() + ", ");
//		sb.append("invoiceidFk: " + this.getInvoiceidFk() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("modifieddate: " + this.getModifieddate() + ", ");
//		sb.append("slotduration: " + this.getSlotduration() + ", ");
//		sb.append("slotendtime: " + this.getSlotendtime() + ", ");
//		sb.append("slotstarttime: " + this.getSlotstarttime() + ", ");
//		sb.append("usercheckin: " + this.getUsercheckin() + ", ");
//		sb.append("usercheckout: " + this.getUsercheckout() + ", ");
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdAppointment that;
//		try {
//			that = (JdAppointment) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getAppointmentdescription() == null) && (that.getAppointmentdescription() == null)) || (getAppointmentdescription() != null && getAppointmentdescription().equals(that.getAppointmentdescription())));
//		result = result && (((getAppointmentstatus() == null) && (that.getAppointmentstatus() == null)) || (getAppointmentstatus() != null && getAppointmentstatus().equals(that.getAppointmentstatus())));
//		result = result && (((getAppointmenttakenby() == null) && (that.getAppointmenttakenby() == null)) || (getAppointmenttakenby() != null && getAppointmenttakenby().equals(that.getAppointmenttakenby())));
//		result = result && (((getAppoitmentstarttime() == null) && (that.getAppoitmentstarttime() == null)) || (getAppoitmentstarttime() != null && getAppoitmentstarttime().equals(that.getAppoitmentstarttime())));
//		result = result && (((getClinicidFk() == null) && (that.getClinicidFk() == null)) || (getClinicidFk() != null && getClinicidFk().getId().equals(that.getClinicidFk().getId())));
//		result = result && (((getCreationdate() == null) && (that.getCreationdate() == null)) || (getCreationdate() != null && getCreationdate().equals(that.getCreationdate())));
//		result = result && (((getInvoiceidFk() == null) && (that.getInvoiceidFk() == null)) || (getInvoiceidFk() != null && getInvoiceidFk().equals(that.getInvoiceidFk())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getModifieddate() == null) && (that.getModifieddate() == null)) || (getModifieddate() != null && getModifieddate().equals(that.getModifieddate())));
//		result = result && (((getSlotduration() == null) && (that.getSlotduration() == null)) || (getSlotduration() != null && getSlotduration().equals(that.getSlotduration())));
//		result = result && (((getSlotendtime() == null) && (that.getSlotendtime() == null)) || (getSlotendtime() != null && getSlotendtime().equals(that.getSlotendtime())));
//		result = result && (((getSlotstarttime() == null) && (that.getSlotstarttime() == null)) || (getSlotstarttime() != null && getSlotstarttime().equals(that.getSlotstarttime())));
//		result = result && (((getUsercheckin() == null) && (that.getUsercheckin() == null)) || (getUsercheckin() != null && getUsercheckin().equals(that.getUsercheckin())));
//		result = result && (((getUsercheckout() == null) && (that.getUsercheckout() == null)) || (getUsercheckout() != null && getUsercheckout().equals(that.getUsercheckout())));
//		result = result && (((getUseridFk() == null) && (that.getUseridFk() == null)) || (getUseridFk() != null && getUseridFk().getId().equals(that.getUseridFk().getId())));
//		return result;
//	}
//
//	/** Calculate the hashcode.
//	 * @see Object#hashCode()
//	 * @return a calculated number
//	 */
//	@Override
//	public int hashCode() {
//		if ( this.hashCode == null ) {
//			synchronized ( this ) {
//				if ( this.hashCode == null ) {
//					Long newHashCode = null;
//
//					if ( getId() != null ) {
//					newHashCode = SAVED_HASHES.get( getId() );
//					}
//
//					if ( newHashCode == null ) {
//						if ( getId() != null && getId() != 0L) {
//							newHashCode = getId();
//						} else {
//							newHashCode = (long) super.hashCode();
//
//						}
//					}
//
//					this.hashCode = newHashCode;
//				}
//			}
//		}
//		return (int) (this.hashCode & 0xffffff);
//	}
//
//
//
//}
