//package com.techstomach.ehs.core;
//
//import java.io.Serializable;
//import java.util.Collections;
//import java.util.Date;
//import java.util.Map;
//import java.util.WeakHashMap;
//import javax.persistence.Basic;
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_booking_slots.
// * @author autogenerated
// */
//
//@Entity
//@Table(name = "jd_booking_slots", catalog = "jdehs_dev")
//public class JdBookingSlots implements Cloneable, Serializable {
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033267L;
//
//	/** Use a WeakHashMap so entries will be garbage collected once all entities
//		referring to a saved hash are garbage collected themselves. */
//	private static final Map<Serializable, Long> SAVED_HASHES =
//		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
//
//	/** hashCode temporary storage. */
//	private volatile Long hashCode;
//
//
//	/** Field mapping. */
//	private JdClinic clinicidFk;
//	/** Field mapping. */
//	private Date datecreated;
//	/** Field mapping. */
//	private Date datemodified;
//	/** Field mapping. */
//	private Long id = 0L; // init for hibernate bug workaround
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Integer slotduration;
//	/** Field mapping. */
//	private Date slotendtime;
//	/** Field mapping. */
//	private Date slotstarttime;
//	/** Field mapping. */
//	private JdUser useridFk;
//	/**
//	 * Default constructor, mainly for hibernate use.
//	 */
//	public JdBookingSlots() {
//		// Default constructor
//	}
//
//	/** Constructor taking a given ID.
//	 * @param id to set
//	 */
//	public JdBookingSlots(Long id) {
//		this.id = id;
//	}
//
//	/** Constructor taking a given ID.
//	 * @param clinicidFk JdClinic object;
//	 * @param datecreated Date object;
//	 * @param datemodified Date object;
//	 * @param id Long object;
//	 * @param modifiedby String object;
//	 * @param slotduration Integer object;
//	 * @param slotendtime Date object;
//	 * @param slotstarttime Date object;
//	 * @param useridFk JdUser object;
//	 */
//	public JdBookingSlots(JdClinic clinicidFk, Date datecreated, Date datemodified,
//			Long id, String modifiedby, Integer slotduration,
//			Date slotendtime, Date slotstarttime, JdUser useridFk) {
//
//		this.clinicidFk = clinicidFk;
//		this.datecreated = datecreated;
//		this.datemodified = datemodified;
//		this.id = id;
//		this.modifiedby = modifiedby;
//		this.slotduration = slotduration;
//		this.slotendtime = slotendtime;
//		this.slotstarttime = slotstarttime;
//		this.useridFk = useridFk;
//	}
//
//
//
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Transient
//	public Class<?> getClassType() {
//		return JdBookingSlots.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: clinicidFk.
//	 * @return A JdClinic object (this.clinicidFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "clinicId_fk", nullable = false )
//	public JdClinic getClinicidFk() {
//		return this.clinicidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: clinicidFk.
//	 * @param clinicidFk the clinicidFk value you wish to set
//	 */
//	public void setClinicidFk(final JdClinic clinicidFk) {
//		this.clinicidFk = clinicidFk;
//	}
//
//    /**
//     * Return the value associated with the column: datecreated.
//	 * @return A Date object (this.datecreated)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getDatecreated() {
//		return this.datecreated;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: datecreated.
//	 * @param datecreated the datecreated value you wish to set
//	 */
//	public void setDatecreated(final Date datecreated) {
//		this.datecreated = datecreated;
//	}
//
//    /**
//     * Return the value associated with the column: datemodified.
//	 * @return A Date object (this.datemodified)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getDatemodified() {
//		return this.datemodified;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: datemodified.
//	 * @param datemodified the datemodified value you wish to set
//	 */
//	public void setDatemodified(final Date datemodified) {
//		this.datemodified = datemodified;
//	}
//
//    /**
//     * Return the value associated with the column: id.
//	 * @return A Long object (this.id)
//	 */
//    @Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Basic( optional = false )
//	@Column( name = "slotid", nullable = false  )
//	public Long getId() {
//		return this.id;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: id.
//	 * @param id the id value you wish to set
//	 */
//	public void setId(final Long id) {
//		// If we've just been persisted and hashCode has been
//		// returned then make sure other entities with this
//		// ID return the already returned hash code
//		if ( (this.id == null || this.id == 0L) &&
//				(id != null) &&
//				(this.hashCode != null) ) {
//		SAVED_HASHES.put( id, this.hashCode );
//		}
//		this.id = id;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: slotduration.
//	 * @return A Integer object (this.slotduration)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Integer getSlotduration() {
//		return this.slotduration;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: slotduration.
//	 * @param slotduration the slotduration value you wish to set
//	 */
//	public void setSlotduration(final Integer slotduration) {
//		this.slotduration = slotduration;
//	}
//
//    /**
//     * Return the value associated with the column: slotendtime.
//	 * @return A Date object (this.slotendtime)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getSlotendtime() {
//		return this.slotendtime;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: slotendtime.
//	 * @param slotendtime the slotendtime value you wish to set
//	 */
//	public void setSlotendtime(final Date slotendtime) {
//		this.slotendtime = slotendtime;
//	}
//
//    /**
//     * Return the value associated with the column: slotstarttime.
//	 * @return A Date object (this.slotstarttime)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getSlotstarttime() {
//		return this.slotstarttime;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: slotstarttime.
//	 * @param slotstarttime the slotstarttime value you wish to set
//	 */
//	public void setSlotstarttime(final Date slotstarttime) {
//		this.slotstarttime = slotstarttime;
//	}
//
//    /**
//     * Return the value associated with the column: useridFk.
//	 * @return A JdUser object (this.useridFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "userId_fk", nullable = false )
//	public JdUser getUseridFk() {
//		return this.useridFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: useridFk.
//	 * @param useridFk the useridFk value you wish to set
//	 */
//	public void setUseridFk(final JdUser useridFk) {
//		this.useridFk = useridFk;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdBookingSlots clone() throws CloneNotSupportedException {
//
//        final JdBookingSlots copy = (JdBookingSlots)super.clone();
//
//		copy.setClinicidFk(this.getClinicidFk());
//		copy.setDatecreated(this.getDatecreated());
//		copy.setDatemodified(this.getDatemodified());
//		copy.setId(this.getId());
//		copy.setModifiedby(this.getModifiedby());
//		copy.setSlotduration(this.getSlotduration());
//		copy.setSlotendtime(this.getSlotendtime());
//		copy.setSlotstarttime(this.getSlotstarttime());
//		copy.setUseridFk(this.getUseridFk());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("datecreated: " + this.getDatecreated() + ", ");
//		sb.append("datemodified: " + this.getDatemodified() + ", ");
//		sb.append("id: " + this.getId() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("slotduration: " + this.getSlotduration() + ", ");
//		sb.append("slotendtime: " + this.getSlotendtime() + ", ");
//		sb.append("slotstarttime: " + this.getSlotstarttime() + ", ");
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdBookingSlots that;
//		try {
//			that = (JdBookingSlots) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getClinicidFk() == null) && (that.getClinicidFk() == null)) || (getClinicidFk() != null && getClinicidFk().getId().equals(that.getClinicidFk().getId())));
//		result = result && (((getDatecreated() == null) && (that.getDatecreated() == null)) || (getDatecreated() != null && getDatecreated().equals(that.getDatecreated())));
//		result = result && (((getDatemodified() == null) && (that.getDatemodified() == null)) || (getDatemodified() != null && getDatemodified().equals(that.getDatemodified())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getSlotduration() == null) && (that.getSlotduration() == null)) || (getSlotduration() != null && getSlotduration().equals(that.getSlotduration())));
//		result = result && (((getSlotendtime() == null) && (that.getSlotendtime() == null)) || (getSlotendtime() != null && getSlotendtime().equals(that.getSlotendtime())));
//		result = result && (((getSlotstarttime() == null) && (that.getSlotstarttime() == null)) || (getSlotstarttime() != null && getSlotstarttime().equals(that.getSlotstarttime())));
//		result = result && (((getUseridFk() == null) && (that.getUseridFk() == null)) || (getUseridFk() != null && getUseridFk().getId().equals(that.getUseridFk().getId())));
//		return result;
//	}
//
//	/** Calculate the hashcode.
//	 * @see Object#hashCode()
//	 * @return a calculated number
//	 */
//	@Override
//	public int hashCode() {
//		if ( this.hashCode == null ) {
//			synchronized ( this ) {
//				if ( this.hashCode == null ) {
//					Long newHashCode = null;
//
//					if ( getId() != null ) {
//					newHashCode = SAVED_HASHES.get( getId() );
//					}
//
//					if ( newHashCode == null ) {
//						if ( getId() != null && getId() != 0L) {
//							newHashCode = getId();
//						} else {
//							newHashCode = (long) super.hashCode();
//
//						}
//					}
//
//					this.hashCode = newHashCode;
//				}
//			}
//		}
//		return (int) (this.hashCode & 0xffffff);
//	}
//
//
//
//}
