//package com.techstomach.ehs.core;
//
//import java.io.Serializable;
//import java.util.Collections;
//import java.util.Date;
//import java.util.HashSet;
//import java.util.Map;
//import java.util.Set;
//import java.util.WeakHashMap;
//import javax.persistence.Basic;
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.OneToMany;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_corporate_package.
// * @author autogenerated
// */
//
//@Entity
//@Table(name = "jd_corporate_package", catalog = "jdehs_dev")
//public class JdCorporatePackage implements Cloneable, Serializable{
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033262L;
//
//	/** Use a WeakHashMap so entries will be garbage collected once all entities
//		referring to a saved hash are garbage collected themselves. */
//	private static final Map<Serializable, Long> SAVED_HASHES =
//		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
//
//	/** hashCode temporary storage. */
//	private volatile Long hashCode;
//
//
//	/** Field mapping. */
//	private String comments;
//	/** Field mapping. */
//	private Date creationdate;
//	/** Field mapping. */
//	private Long id = 0L; // init for hibernate bug workaround
//	/** Field mapping. */
//	private Set<JdCorporatePackageClinicServiceMap> jdCorporatePackageClinicServiceMaps = new HashSet<JdCorporatePackageClinicServiceMap>();
//
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Date modifieddate;
//	/** Field mapping. */
//	private String packagename;
//	/** Field mapping. */
//	private Double servicediscount;
//	/** Field mapping. */
//	private Long serviceidFk;
//	/**
//	 * Default constructor, mainly for hibernate use.
//	 */
//	public JdCorporatePackage() {
//		// Default constructor
//	}
//
//	/** Constructor taking a given ID.
//	 * @param id to set
//	 */
//	public JdCorporatePackage(Long id) {
//		this.id = id;
//	}
//
//	/** Constructor taking a given ID.
//	 * @param id Long object;
//	 * @param modifiedby String object;
//	 * @param packagename String object;
//	 */
//	public JdCorporatePackage(Long id, String modifiedby, String packagename) {
//
//		this.id = id;
//		this.modifiedby = modifiedby;
//		this.packagename = packagename;
//	}
//
//
//
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Transient
//	public Class<?> getClassType() {
//		return JdCorporatePackage.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: comments.
//	 * @return A String object (this.comments)
//	 */
//	@Basic( optional = true )
//	@Column( length = 500  )
//	public String getComments() {
//		return this.comments;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: comments.
//	 * @param comments the comments value you wish to set
//	 */
//	public void setComments(final String comments) {
//		this.comments = comments;
//	}
//
//    /**
//     * Return the value associated with the column: creationdate.
//	 * @return A Date object (this.creationdate)
//	 */
//	public Date getCreationdate() {
//		return this.creationdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: creationdate.
//	 * @param creationdate the creationdate value you wish to set
//	 */
//	public void setCreationdate(final Date creationdate) {
//		this.creationdate = creationdate;
//	}
//
//    /**
//     * Return the value associated with the column: id.
//	 * @return A Long object (this.id)
//	 */
//    @Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Basic( optional = false )
//	@Column( name = "packageid", nullable = false  )
//	public Long getId() {
//		return this.id;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: id.
//	 * @param id the id value you wish to set
//	 */
//	public void setId(final Long id) {
//		// If we've just been persisted and hashCode has been
//		// returned then make sure other entities with this
//		// ID return the already returned hash code
//		if ( (this.id == null || this.id == 0L) &&
//				(id != null) &&
//				(this.hashCode != null) ) {
//		SAVED_HASHES.put( id, this.hashCode );
//		}
//		this.id = id;
//	}
//
//    /**
//     * Return the value associated with the column: jdCorporatePackageClinicServiceMap.
//	 * @return A Set&lt;JdCorporatePackageClinicServiceMap&gt; object (this.jdCorporatePackageClinicServiceMap)
//	 */
// 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "packageidFk"  )
// 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Set<JdCorporatePackageClinicServiceMap> getJdCorporatePackageClinicServiceMaps() {
//		return this.jdCorporatePackageClinicServiceMaps;
//
//	}
//
//	/**
//	 * Adds a bi-directional link of type JdCorporatePackageClinicServiceMap to the jdCorporatePackageClinicServiceMaps set.
//	 * @param jdCorporatePackageClinicServiceMap item to add
//	 */
//	public void addJdCorporatePackageClinicServiceMap(JdCorporatePackageClinicServiceMap jdCorporatePackageClinicServiceMap) {
//		jdCorporatePackageClinicServiceMap.setPackageidFk(this);
//		this.jdCorporatePackageClinicServiceMaps.add(jdCorporatePackageClinicServiceMap);
//	}
//
//
//    /**
//     * Set the value related to the column: jdCorporatePackageClinicServiceMap.
//	 * @param jdCorporatePackageClinicServiceMap the jdCorporatePackageClinicServiceMap value you wish to set
//	 */
//	public void setJdCorporatePackageClinicServiceMaps(final Set<JdCorporatePackageClinicServiceMap> jdCorporatePackageClinicServiceMap) {
//		this.jdCorporatePackageClinicServiceMaps = jdCorporatePackageClinicServiceMap;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: modifieddate.
//	 * @return A Date object (this.modifieddate)
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifieddate.
//	 * @param modifieddate the modifieddate value you wish to set
//	 */
//	public void setModifieddate(final Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//    /**
//     * Return the value associated with the column: packagename.
//	 * @return A String object (this.packagename)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getPackagename() {
//		return this.packagename;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: packagename.
//	 * @param packagename the packagename value you wish to set
//	 */
//	public void setPackagename(final String packagename) {
//		this.packagename = packagename;
//	}
//
//    /**
//     * Return the value associated with the column: servicediscount.
//	 * @return A Double object (this.servicediscount)
//	 */
//	public Double getServicediscount() {
//		return this.servicediscount;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: servicediscount.
//	 * @param servicediscount the servicediscount value you wish to set
//	 */
//	public void setServicediscount(final Double servicediscount) {
//		this.servicediscount = servicediscount;
//	}
//
//    /**
//     * Return the value associated with the column: serviceidFk.
//	 * @return A Long object (this.serviceidFk)
//	 */
//	@Basic( optional = true )
//	@Column( name = "serviceid_fk"  )
//	public Long getServiceidFk() {
//		return this.serviceidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: serviceidFk.
//	 * @param serviceidFk the serviceidFk value you wish to set
//	 */
//	public void setServiceidFk(final Long serviceidFk) {
//		this.serviceidFk = serviceidFk;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdCorporatePackage clone() throws CloneNotSupportedException {
//
//        final JdCorporatePackage copy = (JdCorporatePackage)super.clone();
//
//		copy.setComments(this.getComments());
//		copy.setCreationdate(this.getCreationdate());
//		copy.setId(this.getId());
//		if (this.getJdCorporatePackageClinicServiceMaps() != null) {
//			copy.getJdCorporatePackageClinicServiceMaps().addAll(this.getJdCorporatePackageClinicServiceMaps());
//		}
//		copy.setModifiedby(this.getModifiedby());
//		copy.setModifieddate(this.getModifieddate());
//		copy.setPackagename(this.getPackagename());
//		copy.setServicediscount(this.getServicediscount());
//		copy.setServiceidFk(this.getServiceidFk());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("comments: " + this.getComments() + ", ");
//		sb.append("creationdate: " + this.getCreationdate() + ", ");
//		sb.append("id: " + this.getId() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("modifieddate: " + this.getModifieddate() + ", ");
//		sb.append("packagename: " + this.getPackagename() + ", ");
//		sb.append("servicediscount: " + this.getServicediscount() + ", ");
//		sb.append("serviceidFk: " + this.getServiceidFk());
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdCorporatePackage that;
//		try {
//			that = (JdCorporatePackage) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getComments() == null) && (that.getComments() == null)) || (getComments() != null && getComments().equals(that.getComments())));
//		result = result && (((getCreationdate() == null) && (that.getCreationdate() == null)) || (getCreationdate() != null && getCreationdate().equals(that.getCreationdate())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getModifieddate() == null) && (that.getModifieddate() == null)) || (getModifieddate() != null && getModifieddate().equals(that.getModifieddate())));
//		result = result && (((getPackagename() == null) && (that.getPackagename() == null)) || (getPackagename() != null && getPackagename().equals(that.getPackagename())));
//		result = result && (((getServicediscount() == null) && (that.getServicediscount() == null)) || (getServicediscount() != null && getServicediscount().equals(that.getServicediscount())));
//		result = result && (((getServiceidFk() == null) && (that.getServiceidFk() == null)) || (getServiceidFk() != null && getServiceidFk().equals(that.getServiceidFk())));
//		return result;
//	}
//
//	/** Calculate the hashcode.
//	 * @see Object#hashCode()
//	 * @return a calculated number
//	 */
//	@Override
//	public int hashCode() {
//		if ( this.hashCode == null ) {
//			synchronized ( this ) {
//				if ( this.hashCode == null ) {
//					Long newHashCode = null;
//
//					if ( getId() != null ) {
//					newHashCode = SAVED_HASHES.get( getId() );
//					}
//
//					if ( newHashCode == null ) {
//						if ( getId() != null && getId() != 0L) {
//							newHashCode = getId();
//						} else {
//							newHashCode = (long) super.hashCode();
//
//						}
//					}
//
//					this.hashCode = newHashCode;
//				}
//			}
//		}
//		return (int) (this.hashCode & 0xffffff);
//	}
//
//
//
//}
