//package com.techstomach.ehs.core;
//
//import java.io.Serializable;
//import java.util.Collections;
//import java.util.Date;
//import java.util.Map;
//import java.util.WeakHashMap;
//import javax.persistence.Basic;
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_invoice.
// * @author autogenerated
// */
//
//@Entity
//@Table(name = "jd_invoice", catalog = "jdehs_dev")
//public class JdInvoice implements Cloneable, Serializable {
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033259L;
//
//	/** Use a WeakHashMap so entries will be garbage collected once all entities
//		referring to a saved hash are garbage collected themselves. */
//	private static final Map<Serializable, Long> SAVED_HASHES =
//		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
//
//	/** hashCode temporary storage. */
//	private volatile Long hashCode;
//
//
//	/** Field mapping. */
//	private JdAppointment appointmentidFk;
//	/** Field mapping. */
//	private JdClinic clinicidFk;
//	/** Field mapping. */
//	private Date creationdate;
//	/** Field mapping. */
//	private String description;
//	/** Field mapping. */
//	private Long id = 0L; // init for hibernate bug workaround
//	/** Field mapping. */
//	private Double invoiceamount;
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Date modifieddate;
//	/** Field mapping. */
//	private Date paymentdatetime;
//	/** Field mapping. */
//	private String paymentstatus;
//	/** Field mapping. */
//	private String paymenttype;
//	/** Field mapping. */
//	private String taxamount;
//	/** Field mapping. */
//	private Double totalamount;
//	/** Field mapping. */
//	private JdUser useridFk;
//	/**
//	 * Default constructor, mainly for hibernate use.
//	 */
//	public JdInvoice() {
//		// Default constructor
//	}
//
//	/** Constructor taking a given ID.
//	 * @param id to set
//	 */
//	public JdInvoice(Long id) {
//		this.id = id;
//	}
//
//	/** Constructor taking a given ID.
//	 * @param appointmentidFk JdAppointment object;
//	 * @param clinicidFk JdClinic object;
//	 * @param description String object;
//	 * @param id Long object;
//	 * @param invoiceamount Double object;
//	 * @param modifiedby String object;
//	 * @param paymentdatetime Date object;
//	 * @param paymentstatus String object;
//	 * @param paymenttype String object;
//	 * @param taxamount String object;
//	 * @param totalamount Double object;
//	 * @param useridFk JdUser object;
//	 */
//	public JdInvoice(JdAppointment appointmentidFk, JdClinic clinicidFk, String description,
//			Long id, Double invoiceamount, String modifiedby,
//			Date paymentdatetime, String paymentstatus, String paymenttype,
//			String taxamount, Double totalamount, JdUser useridFk) {
//
//		this.appointmentidFk = appointmentidFk;
//		this.clinicidFk = clinicidFk;
//		this.description = description;
//		this.id = id;
//		this.invoiceamount = invoiceamount;
//		this.modifiedby = modifiedby;
//		this.paymentdatetime = paymentdatetime;
//		this.paymentstatus = paymentstatus;
//		this.paymenttype = paymenttype;
//		this.taxamount = taxamount;
//		this.totalamount = totalamount;
//		this.useridFk = useridFk;
//	}
//
//
//
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Transient
//	public Class<?> getClassType() {
//		return JdInvoice.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: appointmentidFk.
//	 * @return A JdAppointment object (this.appointmentidFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "appointmentId_fk", nullable = false )
//	public JdAppointment getAppointmentidFk() {
//		return this.appointmentidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: appointmentidFk.
//	 * @param appointmentidFk the appointmentidFk value you wish to set
//	 */
//	public void setAppointmentidFk(final JdAppointment appointmentidFk) {
//		this.appointmentidFk = appointmentidFk;
//	}
//
//    /**
//     * Return the value associated with the column: clinicidFk.
//	 * @return A JdClinic object (this.clinicidFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "clinicId_fk", nullable = false )
//	public JdClinic getClinicidFk() {
//		return this.clinicidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: clinicidFk.
//	 * @param clinicidFk the clinicidFk value you wish to set
//	 */
//	public void setClinicidFk(final JdClinic clinicidFk) {
//		this.clinicidFk = clinicidFk;
//	}
//
//    /**
//     * Return the value associated with the column: creationdate.
//	 * @return A Date object (this.creationdate)
//	 */
//	public Date getCreationdate() {
//		return this.creationdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: creationdate.
//	 * @param creationdate the creationdate value you wish to set
//	 */
//	public void setCreationdate(final Date creationdate) {
//		this.creationdate = creationdate;
//	}
//
//    /**
//     * Return the value associated with the column: description.
//	 * @return A String object (this.description)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getDescription() {
//		return this.description;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: description.
//	 * @param description the description value you wish to set
//	 */
//	public void setDescription(final String description) {
//		this.description = description;
//	}
//
//    /**
//     * Return the value associated with the column: id.
//	 * @return A Long object (this.id)
//	 */
//    @Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Basic( optional = false )
//	@Column( name = "invoiceid", nullable = false  )
//	public Long getId() {
//		return this.id;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: id.
//	 * @param id the id value you wish to set
//	 */
//	public void setId(final Long id) {
//		// If we've just been persisted and hashCode has been
//		// returned then make sure other entities with this
//		// ID return the already returned hash code
//		if ( (this.id == null || this.id == 0L) &&
//				(id != null) &&
//				(this.hashCode != null) ) {
//		SAVED_HASHES.put( id, this.hashCode );
//		}
//		this.id = id;
//	}
//
//    /**
//     * Return the value associated with the column: invoiceamount.
//	 * @return A Double object (this.invoiceamount)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Double getInvoiceamount() {
//		return this.invoiceamount;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: invoiceamount.
//	 * @param invoiceamount the invoiceamount value you wish to set
//	 */
//	public void setInvoiceamount(final Double invoiceamount) {
//		this.invoiceamount = invoiceamount;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: modifieddate.
//	 * @return A Date object (this.modifieddate)
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifieddate.
//	 * @param modifieddate the modifieddate value you wish to set
//	 */
//	public void setModifieddate(final Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//    /**
//     * Return the value associated with the column: paymentdatetime.
//	 * @return A Date object (this.paymentdatetime)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getPaymentdatetime() {
//		return this.paymentdatetime;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: paymentdatetime.
//	 * @param paymentdatetime the paymentdatetime value you wish to set
//	 */
//	public void setPaymentdatetime(final Date paymentdatetime) {
//		this.paymentdatetime = paymentdatetime;
//	}
//
//    /**
//     * Return the value associated with the column: paymentstatus.
//	 * @return A String object (this.paymentstatus)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getPaymentstatus() {
//		return this.paymentstatus;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: paymentstatus.
//	 * @param paymentstatus the paymentstatus value you wish to set
//	 */
//	public void setPaymentstatus(final String paymentstatus) {
//		this.paymentstatus = paymentstatus;
//	}
//
//    /**
//     * Return the value associated with the column: paymenttype.
//	 * @return A String object (this.paymenttype)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getPaymenttype() {
//		return this.paymenttype;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: paymenttype.
//	 * @param paymenttype the paymenttype value you wish to set
//	 */
//	public void setPaymenttype(final String paymenttype) {
//		this.paymenttype = paymenttype;
//	}
//
//    /**
//     * Return the value associated with the column: taxamount.
//	 * @return A String object (this.taxamount)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getTaxamount() {
//		return this.taxamount;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: taxamount.
//	 * @param taxamount the taxamount value you wish to set
//	 */
//	public void setTaxamount(final String taxamount) {
//		this.taxamount = taxamount;
//	}
//
//    /**
//     * Return the value associated with the column: totalamount.
//	 * @return A Double object (this.totalamount)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Double getTotalamount() {
//		return this.totalamount;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: totalamount.
//	 * @param totalamount the totalamount value you wish to set
//	 */
//	public void setTotalamount(final Double totalamount) {
//		this.totalamount = totalamount;
//	}
//
//    /**
//     * Return the value associated with the column: useridFk.
//	 * @return A JdUser object (this.useridFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "userId_fk", nullable = false )
//	public JdUser getUseridFk() {
//		return this.useridFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: useridFk.
//	 * @param useridFk the useridFk value you wish to set
//	 */
//	public void setUseridFk(final JdUser useridFk) {
//		this.useridFk = useridFk;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdInvoice clone() throws CloneNotSupportedException {
//
//        final JdInvoice copy = (JdInvoice)super.clone();
//
//		copy.setAppointmentidFk(this.getAppointmentidFk());
//		copy.setClinicidFk(this.getClinicidFk());
//		copy.setCreationdate(this.getCreationdate());
//		copy.setDescription(this.getDescription());
//		copy.setId(this.getId());
//		copy.setInvoiceamount(this.getInvoiceamount());
//		copy.setModifiedby(this.getModifiedby());
//		copy.setModifieddate(this.getModifieddate());
//		copy.setPaymentdatetime(this.getPaymentdatetime());
//		copy.setPaymentstatus(this.getPaymentstatus());
//		copy.setPaymenttype(this.getPaymenttype());
//		copy.setTaxamount(this.getTaxamount());
//		copy.setTotalamount(this.getTotalamount());
//		copy.setUseridFk(this.getUseridFk());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("creationdate: " + this.getCreationdate() + ", ");
//		sb.append("description: " + this.getDescription() + ", ");
//		sb.append("id: " + this.getId() + ", ");
//		sb.append("invoiceamount: " + this.getInvoiceamount() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("modifieddate: " + this.getModifieddate() + ", ");
//		sb.append("paymentdatetime: " + this.getPaymentdatetime() + ", ");
//		sb.append("paymentstatus: " + this.getPaymentstatus() + ", ");
//		sb.append("paymenttype: " + this.getPaymenttype() + ", ");
//		sb.append("taxamount: " + this.getTaxamount() + ", ");
//		sb.append("totalamount: " + this.getTotalamount() + ", ");
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdInvoice that;
//		try {
//			that = (JdInvoice) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getAppointmentidFk() == null) && (that.getAppointmentidFk() == null)) || (getAppointmentidFk() != null && getAppointmentidFk().getId().equals(that.getAppointmentidFk().getId())));
//		result = result && (((getClinicidFk() == null) && (that.getClinicidFk() == null)) || (getClinicidFk() != null && getClinicidFk().getId().equals(that.getClinicidFk().getId())));
//		result = result && (((getCreationdate() == null) && (that.getCreationdate() == null)) || (getCreationdate() != null && getCreationdate().equals(that.getCreationdate())));
//		result = result && (((getDescription() == null) && (that.getDescription() == null)) || (getDescription() != null && getDescription().equals(that.getDescription())));
//		result = result && (((getInvoiceamount() == null) && (that.getInvoiceamount() == null)) || (getInvoiceamount() != null && getInvoiceamount().equals(that.getInvoiceamount())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getModifieddate() == null) && (that.getModifieddate() == null)) || (getModifieddate() != null && getModifieddate().equals(that.getModifieddate())));
//		result = result && (((getPaymentdatetime() == null) && (that.getPaymentdatetime() == null)) || (getPaymentdatetime() != null && getPaymentdatetime().equals(that.getPaymentdatetime())));
//		result = result && (((getPaymentstatus() == null) && (that.getPaymentstatus() == null)) || (getPaymentstatus() != null && getPaymentstatus().equals(that.getPaymentstatus())));
//		result = result && (((getPaymenttype() == null) && (that.getPaymenttype() == null)) || (getPaymenttype() != null && getPaymenttype().equals(that.getPaymenttype())));
//		result = result && (((getTaxamount() == null) && (that.getTaxamount() == null)) || (getTaxamount() != null && getTaxamount().equals(that.getTaxamount())));
//		result = result && (((getTotalamount() == null) && (that.getTotalamount() == null)) || (getTotalamount() != null && getTotalamount().equals(that.getTotalamount())));
//		result = result && (((getUseridFk() == null) && (that.getUseridFk() == null)) || (getUseridFk() != null && getUseridFk().getId().equals(that.getUseridFk().getId())));
//		return result;
//	}
//
//	/** Calculate the hashcode.
//	 * @see Object#hashCode()
//	 * @return a calculated number
//	 */
//	@Override
//	public int hashCode() {
//		if ( this.hashCode == null ) {
//			synchronized ( this ) {
//				if ( this.hashCode == null ) {
//					Long newHashCode = null;
//
//					if ( getId() != null ) {
//					newHashCode = SAVED_HASHES.get( getId() );
//					}
//
//					if ( newHashCode == null ) {
//						if ( getId() != null && getId() != 0L) {
//							newHashCode = getId();
//						} else {
//							newHashCode = (long) super.hashCode();
//
//						}
//					}
//
//					this.hashCode = newHashCode;
//				}
//			}
//		}
//		return (int) (this.hashCode & 0xffffff);
//	}
//
//
//
//}
