//package com.techstomach.ehs.core;
//
//import java.io.Serializable;
//import java.util.Collections;
//import java.util.Date;
//import java.util.Map;
//import java.util.WeakHashMap;
//import javax.persistence.Basic;
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_patient_medication.
// * @author autogenerated
// */
//
//@Entity
//@Table(name = "jd_patient_medication", catalog = "jdehs_dev")
//public class JdPatientMedication implements Cloneable, Serializable {
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033254L;
//
//	/** Use a WeakHashMap so entries will be garbage collected once all entities
//		referring to a saved hash are garbage collected themselves. */
//	private static final Map<Serializable, Long> SAVED_HASHES =
//		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
//
//	/** hashCode temporary storage. */
//	private volatile Long hashCode;
//
//
//	/** Field mapping. */
//	private Long appointmentidFk;
//	/** Field mapping. */
//	private JdClinic clinicidFk;
//	/** Field mapping. */
//	private Date creationdate;
//	/** Field mapping. */
//	private Date enddate;
//	/** Field mapping. */
//	private Long id = 0L; // init for hibernate bug workaround
//	/** Field mapping. */
//	private String instructions;
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Date modifieddate;
//	/** Field mapping. */
//	private Long procedureid;
//	/** Field mapping. */
//	private Date startdate;
//	/** Field mapping. */
//	private JdUser useridFk;
//	/**
//	 * Default constructor, mainly for hibernate use.
//	 */
//	public JdPatientMedication() {
//		// Default constructor
//	}
//
//	/** Constructor taking a given ID.
//	 * @param id to set
//	 */
//	public JdPatientMedication(Long id) {
//		this.id = id;
//	}
//
//	/** Constructor taking a given ID.
//	 * @param clinicidFk JdClinic object;
//	 * @param enddate Date object;
//	 * @param id Long object;
//	 * @param instructions String object;
//	 * @param modifiedby String object;
//	 * @param startdate Date object;
//	 * @param useridFk JdUser object;
//	 */
//	public JdPatientMedication(JdClinic clinicidFk, Date enddate, Long id,
//			String instructions, String modifiedby, Date startdate,
//			JdUser useridFk) {
//
//		this.clinicidFk = clinicidFk;
//		this.enddate = enddate;
//		this.id = id;
//		this.instructions = instructions;
//		this.modifiedby = modifiedby;
//		this.startdate = startdate;
//		this.useridFk = useridFk;
//	}
//
//
//
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Transient
//	public Class<?> getClassType() {
//		return JdPatientMedication.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: appointmentidFk.
//	 * @return A Long object (this.appointmentidFk)
//	 */
//	@Basic( optional = true )
//	@Column( name = "appointmentid_fk"  )
//	public Long getAppointmentidFk() {
//		return this.appointmentidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: appointmentidFk.
//	 * @param appointmentidFk the appointmentidFk value you wish to set
//	 */
//	public void setAppointmentidFk(final Long appointmentidFk) {
//		this.appointmentidFk = appointmentidFk;
//	}
//
//    /**
//     * Return the value associated with the column: clinicidFk.
//	 * @return A JdClinic object (this.clinicidFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "clinicId_fk", nullable = false )
//	public JdClinic getClinicidFk() {
//		return this.clinicidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: clinicidFk.
//	 * @param clinicidFk the clinicidFk value you wish to set
//	 */
//	public void setClinicidFk(final JdClinic clinicidFk) {
//		this.clinicidFk = clinicidFk;
//	}
//
//    /**
//     * Return the value associated with the column: creationdate.
//	 * @return A Date object (this.creationdate)
//	 */
//	public Date getCreationdate() {
//		return this.creationdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: creationdate.
//	 * @param creationdate the creationdate value you wish to set
//	 */
//	public void setCreationdate(final Date creationdate) {
//		this.creationdate = creationdate;
//	}
//
//    /**
//     * Return the value associated with the column: enddate.
//	 * @return A Date object (this.enddate)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getEnddate() {
//		return this.enddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: enddate.
//	 * @param enddate the enddate value you wish to set
//	 */
//	public void setEnddate(final Date enddate) {
//		this.enddate = enddate;
//	}
//
//    /**
//     * Return the value associated with the column: id.
//	 * @return A Long object (this.id)
//	 */
//    @Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Basic( optional = false )
//	@Column( name = "patientmedicationid", nullable = false  )
//	public Long getId() {
//		return this.id;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: id.
//	 * @param id the id value you wish to set
//	 */
//	public void setId(final Long id) {
//		// If we've just been persisted and hashCode has been
//		// returned then make sure other entities with this
//		// ID return the already returned hash code
//		if ( (this.id == null || this.id == 0L) &&
//				(id != null) &&
//				(this.hashCode != null) ) {
//		SAVED_HASHES.put( id, this.hashCode );
//		}
//		this.id = id;
//	}
//
//    /**
//     * Return the value associated with the column: instructions.
//	 * @return A String object (this.instructions)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getInstructions() {
//		return this.instructions;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: instructions.
//	 * @param instructions the instructions value you wish to set
//	 */
//	public void setInstructions(final String instructions) {
//		this.instructions = instructions;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: modifieddate.
//	 * @return A Date object (this.modifieddate)
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifieddate.
//	 * @param modifieddate the modifieddate value you wish to set
//	 */
//	public void setModifieddate(final Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//    /**
//     * Return the value associated with the column: procedureid.
//	 * @return A Long object (this.procedureid)
//	 */
//	public Long getProcedureid() {
//		return this.procedureid;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: procedureid.
//	 * @param procedureid the procedureid value you wish to set
//	 */
//	public void setProcedureid(final Long procedureid) {
//		this.procedureid = procedureid;
//	}
//
//    /**
//     * Return the value associated with the column: startdate.
//	 * @return A Date object (this.startdate)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getStartdate() {
//		return this.startdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: startdate.
//	 * @param startdate the startdate value you wish to set
//	 */
//	public void setStartdate(final Date startdate) {
//		this.startdate = startdate;
//	}
//
//    /**
//     * Return the value associated with the column: useridFk.
//	 * @return A JdUser object (this.useridFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "userId_fk", nullable = false )
//	public JdUser getUseridFk() {
//		return this.useridFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: useridFk.
//	 * @param useridFk the useridFk value you wish to set
//	 */
//	public void setUseridFk(final JdUser useridFk) {
//		this.useridFk = useridFk;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdPatientMedication clone() throws CloneNotSupportedException {
//
//        final JdPatientMedication copy = (JdPatientMedication)super.clone();
//
//		copy.setAppointmentidFk(this.getAppointmentidFk());
//		copy.setClinicidFk(this.getClinicidFk());
//		copy.setCreationdate(this.getCreationdate());
//		copy.setEnddate(this.getEnddate());
//		copy.setId(this.getId());
//		copy.setInstructions(this.getInstructions());
//		copy.setModifiedby(this.getModifiedby());
//		copy.setModifieddate(this.getModifieddate());
//		copy.setProcedureid(this.getProcedureid());
//		copy.setStartdate(this.getStartdate());
//		copy.setUseridFk(this.getUseridFk());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("appointmentidFk: " + this.getAppointmentidFk() + ", ");
//		sb.append("creationdate: " + this.getCreationdate() + ", ");
//		sb.append("enddate: " + this.getEnddate() + ", ");
//		sb.append("id: " + this.getId() + ", ");
//		sb.append("instructions: " + this.getInstructions() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("modifieddate: " + this.getModifieddate() + ", ");
//		sb.append("procedureid: " + this.getProcedureid() + ", ");
//		sb.append("startdate: " + this.getStartdate() + ", ");
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdPatientMedication that;
//		try {
//			that = (JdPatientMedication) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getAppointmentidFk() == null) && (that.getAppointmentidFk() == null)) || (getAppointmentidFk() != null && getAppointmentidFk().equals(that.getAppointmentidFk())));
//		result = result && (((getClinicidFk() == null) && (that.getClinicidFk() == null)) || (getClinicidFk() != null && getClinicidFk().getId().equals(that.getClinicidFk().getId())));
//		result = result && (((getCreationdate() == null) && (that.getCreationdate() == null)) || (getCreationdate() != null && getCreationdate().equals(that.getCreationdate())));
//		result = result && (((getEnddate() == null) && (that.getEnddate() == null)) || (getEnddate() != null && getEnddate().equals(that.getEnddate())));
//		result = result && (((getInstructions() == null) && (that.getInstructions() == null)) || (getInstructions() != null && getInstructions().equals(that.getInstructions())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getModifieddate() == null) && (that.getModifieddate() == null)) || (getModifieddate() != null && getModifieddate().equals(that.getModifieddate())));
//		result = result && (((getProcedureid() == null) && (that.getProcedureid() == null)) || (getProcedureid() != null && getProcedureid().equals(that.getProcedureid())));
//		result = result && (((getStartdate() == null) && (that.getStartdate() == null)) || (getStartdate() != null && getStartdate().equals(that.getStartdate())));
//		result = result && (((getUseridFk() == null) && (that.getUseridFk() == null)) || (getUseridFk() != null && getUseridFk().getId().equals(that.getUseridFk().getId())));
//		return result;
//	}
//
//	/** Calculate the hashcode.
//	 * @see Object#hashCode()
//	 * @return a calculated number
//	 */
//	@Override
//	public int hashCode() {
//		if ( this.hashCode == null ) {
//			synchronized ( this ) {
//				if ( this.hashCode == null ) {
//					Long newHashCode = null;
//
//					if ( getId() != null ) {
//					newHashCode = SAVED_HASHES.get( getId() );
//					}
//
//					if ( newHashCode == null ) {
//						if ( getId() != null && getId() != 0L) {
//							newHashCode = getId();
//						} else {
//							newHashCode = (long) super.hashCode();
//
//						}
//					}
//
//					this.hashCode = newHashCode;
//				}
//			}
//		}
//		return (int) (this.hashCode & 0xffffff);
//	}
//
//
//
//}
