//package com.techstomach.ehs.core;
//
//import java.util.Date;
//import javax.persistence.Basic;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.PrimaryKeyJoinColumn;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_patient.
// * @author autogenerated
// */
//
//@Entity
//@PrimaryKeyJoinColumn(name = "userid_fk")
//@Table(name = "jd_patient", catalog = "jdehs_dev")
//public class JdPatient extends JdUser {
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033256L;
//
//
//
//	/** Field mapping. */
//	private String aadharnumber;
//	/** Field mapping. */
//	private String bloodgroup;
//	/** Field mapping. */
//	private String city;
//	/** Field mapping. */
//	private String country;
//	/** Field mapping. */
//	private Date creationdate;
//	/** Field mapping. */
//	private Date dateofbirth;
//	/** Field mapping. */
//	private String education;
//	/** Field mapping. */
//	private String emailaddress;
//	/** Field mapping. */
//	private String emergencycontactname;
//	/** Field mapping. */
//	private String emergencycontactnumber;
//	/** Field mapping. */
//	private String emergencycontactrelationship;
//	/** Field mapping. */
//	private String familyhistory;
//	/** Field mapping. */
//	private String firstname;
//	/** Field mapping. */
//	private String gender;
//	/** Field mapping. */
//	private String habbits;
//	/** Field mapping. */
//	private Date insuranceexpiration;
//	/** Field mapping. */
//	private String insurancenumber;
//	/** Field mapping. */
//	private String lastname;
//	/** Field mapping. */
//	private String lcality;
//	/** Field mapping. */
//	private String maritalstatus;
//	/** Field mapping. */
//	private String medicalhistory;
//	/** Field mapping. */
//	private String middlename;
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Date modifieddate;
//	/** Field mapping. */
//	private String occupation;
//	/** Field mapping. */
//	private Long packageidFk;
//	/** Field mapping. */
//	private String patientdisplayid;
//	/** Field mapping. */
//	private String patientnote;
//	/** Field mapping. */
//	private String phonenumber;
//	/** Field mapping. */
//	private Long pincode;
//	/** Field mapping. */
//	private String placeofbirth;
//	/** Field mapping. */
//	private String religion;
//	/** Field mapping. */
//	private String socialhistory;
//	/** Field mapping. */
//	private String state;
//	/** Field mapping. */
//	private String street1;
//	/** Field mapping. */
//	private String street2;
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Override
//	@Transient
//	public Class<?> getClassType() {
//		return JdPatient.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: aadharnumber.
//	 * @return A String object (this.aadharnumber)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getAadharnumber() {
//		return this.aadharnumber;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: aadharnumber.
//	 * @param aadharnumber the aadharnumber value you wish to set
//	 */
//	public void setAadharnumber(final String aadharnumber) {
//		this.aadharnumber = aadharnumber;
//	}
//
//    /**
//     * Return the value associated with the column: bloodgroup.
//	 * @return A String object (this.bloodgroup)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 100  )
//	public String getBloodgroup() {
//		return this.bloodgroup;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: bloodgroup.
//	 * @param bloodgroup the bloodgroup value you wish to set
//	 */
//	public void setBloodgroup(final String bloodgroup) {
//		this.bloodgroup = bloodgroup;
//	}
//
//    /**
//     * Return the value associated with the column: city.
//	 * @return A String object (this.city)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getCity() {
//		return this.city;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: city.
//	 * @param city the city value you wish to set
//	 */
//	public void setCity(final String city) {
//		this.city = city;
//	}
//
//    /**
//     * Return the value associated with the column: country.
//	 * @return A String object (this.country)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getCountry() {
//		return this.country;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: country.
//	 * @param country the country value you wish to set
//	 */
//	public void setCountry(final String country) {
//		this.country = country;
//	}
//
//    /**
//     * Return the value associated with the column: creationdate.
//	 * @return A Date object (this.creationdate)
//	 */
//	public Date getCreationdate() {
//		return this.creationdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: creationdate.
//	 * @param creationdate the creationdate value you wish to set
//	 */
//	public void setCreationdate(final Date creationdate) {
//		this.creationdate = creationdate;
//	}
//
//    /**
//     * Return the value associated with the column: dateofbirth.
//	 * @return A Date object (this.dateofbirth)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Date getDateofbirth() {
//		return this.dateofbirth;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: dateofbirth.
//	 * @param dateofbirth the dateofbirth value you wish to set
//	 */
//	public void setDateofbirth(final Date dateofbirth) {
//		this.dateofbirth = dateofbirth;
//	}
//
//    /**
//     * Return the value associated with the column: education.
//	 * @return A String object (this.education)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getEducation() {
//		return this.education;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: education.
//	 * @param education the education value you wish to set
//	 */
//	public void setEducation(final String education) {
//		this.education = education;
//	}
//
//    /**
//     * Return the value associated with the column: emailaddress.
//	 * @return A String object (this.emailaddress)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	@Override
//	public String getEmailaddress() {
//		return this.emailaddress;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: emailaddress.
//	 * @param emailaddress the emailaddress value you wish to set
//	 */
//	@Override
//	public void setEmailaddress(final String emailaddress) {
//		this.emailaddress = emailaddress;
//	}
//
//    /**
//     * Return the value associated with the column: emergencycontactname.
//	 * @return A String object (this.emergencycontactname)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getEmergencycontactname() {
//		return this.emergencycontactname;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: emergencycontactname.
//	 * @param emergencycontactname the emergencycontactname value you wish to set
//	 */
//	public void setEmergencycontactname(final String emergencycontactname) {
//		this.emergencycontactname = emergencycontactname;
//	}
//
//    /**
//     * Return the value associated with the column: emergencycontactnumber.
//	 * @return A String object (this.emergencycontactnumber)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getEmergencycontactnumber() {
//		return this.emergencycontactnumber;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: emergencycontactnumber.
//	 * @param emergencycontactnumber the emergencycontactnumber value you wish to set
//	 */
//	public void setEmergencycontactnumber(final String emergencycontactnumber) {
//		this.emergencycontactnumber = emergencycontactnumber;
//	}
//
//    /**
//     * Return the value associated with the column: emergencycontactrelationship.
//	 * @return A String object (this.emergencycontactrelationship)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getEmergencycontactrelationship() {
//		return this.emergencycontactrelationship;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: emergencycontactrelationship.
//	 * @param emergencycontactrelationship the emergencycontactrelationship value you wish to set
//	 */
//	public void setEmergencycontactrelationship(final String emergencycontactrelationship) {
//		this.emergencycontactrelationship = emergencycontactrelationship;
//	}
//
//    /**
//     * Return the value associated with the column: familyhistory.
//	 * @return A String object (this.familyhistory)
//	 */
//	@Basic( optional = true )
//	@Column( length = 715827882  )
//	public String getFamilyhistory() {
//		return this.familyhistory;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: familyhistory.
//	 * @param familyhistory the familyhistory value you wish to set
//	 */
//	public void setFamilyhistory(final String familyhistory) {
//		this.familyhistory = familyhistory;
//	}
//
//    /**
//     * Return the value associated with the column: firstname.
//	 * @return A String object (this.firstname)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	@Override
//	public String getFirstname() {
//		return this.firstname;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: firstname.
//	 * @param firstname the firstname value you wish to set
//	 */
//	@Override
//	public void setFirstname(final String firstname) {
//		this.firstname = firstname;
//	}
//
//    /**
//     * Return the value associated with the column: gender.
//	 * @return A String object (this.gender)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 100  )
//	public String getGender() {
//		return this.gender;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: gender.
//	 * @param gender the gender value you wish to set
//	 */
//	public void setGender(final String gender) {
//		this.gender = gender;
//	}
//
//    /**
//     * Return the value associated with the column: habbits.
//	 * @return A String object (this.habbits)
//	 */
//	@Basic( optional = true )
//	@Column( length = 21845  )
//	public String getHabbits() {
//		return this.habbits;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: habbits.
//	 * @param habbits the habbits value you wish to set
//	 */
//	public void setHabbits(final String habbits) {
//		this.habbits = habbits;
//	}
//
//    /**
//     * Return the value associated with the column: insuranceexpiration.
//	 * @return A Date object (this.insuranceexpiration)
//	 */
//	public Date getInsuranceexpiration() {
//		return this.insuranceexpiration;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: insuranceexpiration.
//	 * @param insuranceexpiration the insuranceexpiration value you wish to set
//	 */
//	public void setInsuranceexpiration(final Date insuranceexpiration) {
//		this.insuranceexpiration = insuranceexpiration;
//	}
//
//    /**
//     * Return the value associated with the column: insurancenumber.
//	 * @return A String object (this.insurancenumber)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getInsurancenumber() {
//		return this.insurancenumber;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: insurancenumber.
//	 * @param insurancenumber the insurancenumber value you wish to set
//	 */
//	public void setInsurancenumber(final String insurancenumber) {
//		this.insurancenumber = insurancenumber;
//	}
//
//    /**
//     * Return the value associated with the column: lastname.
//	 * @return A String object (this.lastname)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	@Override
//	public String getLastname() {
//		return this.lastname;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: lastname.
//	 * @param lastname the lastname value you wish to set
//	 */
//	@Override
//	public void setLastname(final String lastname) {
//		this.lastname = lastname;
//	}
//
//    /**
//     * Return the value associated with the column: lcality.
//	 * @return A String object (this.lcality)
//	 */
//	@Basic( optional = true )
//	@Column( length = 500  )
//	public String getLcality() {
//		return this.lcality;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: lcality.
//	 * @param lcality the lcality value you wish to set
//	 */
//	public void setLcality(final String lcality) {
//		this.lcality = lcality;
//	}
//
//    /**
//     * Return the value associated with the column: maritalstatus.
//	 * @return A String object (this.maritalstatus)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 100  )
//	public String getMaritalstatus() {
//		return this.maritalstatus;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: maritalstatus.
//	 * @param maritalstatus the maritalstatus value you wish to set
//	 */
//	public void setMaritalstatus(final String maritalstatus) {
//		this.maritalstatus = maritalstatus;
//	}
//
//    /**
//     * Return the value associated with the column: medicalhistory.
//	 * @return A String object (this.medicalhistory)
//	 */
//	@Basic( optional = true )
//	@Column( length = 715827882  )
//	public String getMedicalhistory() {
//		return this.medicalhistory;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: medicalhistory.
//	 * @param medicalhistory the medicalhistory value you wish to set
//	 */
//	public void setMedicalhistory(final String medicalhistory) {
//		this.medicalhistory = medicalhistory;
//	}
//
//    /**
//     * Return the value associated with the column: middlename.
//	 * @return A String object (this.middlename)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	@Override
//	public String getMiddlename() {
//		return this.middlename;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: middlename.
//	 * @param middlename the middlename value you wish to set
//	 */
//	@Override
//	public void setMiddlename(final String middlename) {
//		this.middlename = middlename;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	@Override
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	@Override
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: modifieddate.
//	 * @return A Date object (this.modifieddate)
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifieddate.
//	 * @param modifieddate the modifieddate value you wish to set
//	 */
//	public void setModifieddate(final Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//    /**
//     * Return the value associated with the column: occupation.
//	 * @return A String object (this.occupation)
//	 */
//	@Basic( optional = true )
//	@Column( length = 255  )
//	public String getOccupation() {
//		return this.occupation;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: occupation.
//	 * @param occupation the occupation value you wish to set
//	 */
//	public void setOccupation(final String occupation) {
//		this.occupation = occupation;
//	}
//
//    /**
//     * Return the value associated with the column: packageidFk.
//	 * @return A Long object (this.packageidFk)
//	 */
//	@Basic( optional = false )
//	@Column( name = "packageid_fk", nullable = false  )
//	public Long getPackageidFk() {
//		return this.packageidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: packageidFk.
//	 * @param packageidFk the packageidFk value you wish to set
//	 */
//	public void setPackageidFk(final Long packageidFk) {
//		this.packageidFk = packageidFk;
//	}
//
//    /**
//     * Return the value associated with the column: patientdisplayid.
//	 * @return A String object (this.patientdisplayid)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getPatientdisplayid() {
//		return this.patientdisplayid;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: patientdisplayid.
//	 * @param patientdisplayid the patientdisplayid value you wish to set
//	 */
//	public void setPatientdisplayid(final String patientdisplayid) {
//		this.patientdisplayid = patientdisplayid;
//	}
//
//    /**
//     * Return the value associated with the column: patientnote.
//	 * @return A String object (this.patientnote)
//	 */
//	@Basic( optional = true )
//	@Column( length = 715827882  )
//	public String getPatientnote() {
//		return this.patientnote;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: patientnote.
//	 * @param patientnote the patientnote value you wish to set
//	 */
//	public void setPatientnote(final String patientnote) {
//		this.patientnote = patientnote;
//	}
//
//    /**
//     * Return the value associated with the column: phonenumber.
//	 * @return A String object (this.phonenumber)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	@Override
//	public String getPhonenumber() {
//		return this.phonenumber;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: phonenumber.
//	 * @param phonenumber the phonenumber value you wish to set
//	 */
//	@Override
//	public void setPhonenumber(final String phonenumber) {
//		this.phonenumber = phonenumber;
//	}
//
//    /**
//     * Return the value associated with the column: pincode.
//	 * @return A Long object (this.pincode)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Long getPincode() {
//		return this.pincode;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: pincode.
//	 * @param pincode the pincode value you wish to set
//	 */
//	public void setPincode(final Long pincode) {
//		this.pincode = pincode;
//	}
//
//    /**
//     * Return the value associated with the column: placeofbirth.
//	 * @return A String object (this.placeofbirth)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getPlaceofbirth() {
//		return this.placeofbirth;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: placeofbirth.
//	 * @param placeofbirth the placeofbirth value you wish to set
//	 */
//	public void setPlaceofbirth(final String placeofbirth) {
//		this.placeofbirth = placeofbirth;
//	}
//
//    /**
//     * Return the value associated with the column: religion.
//	 * @return A String object (this.religion)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 100  )
//	public String getReligion() {
//		return this.religion;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: religion.
//	 * @param religion the religion value you wish to set
//	 */
//	public void setReligion(final String religion) {
//		this.religion = religion;
//	}
//
//    /**
//     * Return the value associated with the column: socialhistory.
//	 * @return A String object (this.socialhistory)
//	 */
//	@Basic( optional = true )
//	@Column( length = 715827882  )
//	public String getSocialhistory() {
//		return this.socialhistory;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: socialhistory.
//	 * @param socialhistory the socialhistory value you wish to set
//	 */
//	public void setSocialhistory(final String socialhistory) {
//		this.socialhistory = socialhistory;
//	}
//
//    /**
//     * Return the value associated with the column: state.
//	 * @return A String object (this.state)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getState() {
//		return this.state;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: state.
//	 * @param state the state value you wish to set
//	 */
//	public void setState(final String state) {
//		this.state = state;
//	}
//
//    /**
//     * Return the value associated with the column: street1.
//	 * @return A String object (this.street1)
//	 */
//	@Basic( optional = true )
//	@Column( length = 1000  )
//	public String getStreet1() {
//		return this.street1;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: street1.
//	 * @param street1 the street1 value you wish to set
//	 */
//	public void setStreet1(final String street1) {
//		this.street1 = street1;
//	}
//
//    /**
//     * Return the value associated with the column: street2.
//	 * @return A String object (this.street2)
//	 */
//	@Basic( optional = true )
//	@Column( length = 1000  )
//	public String getStreet2() {
//		return this.street2;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: street2.
//	 * @param street2 the street2 value you wish to set
//	 */
//	public void setStreet2(final String street2) {
//		this.street2 = street2;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdPatient clone() throws CloneNotSupportedException {
//
//        final JdPatient copy = (JdPatient)super.clone();
//
//		copy.setAadharnumber(this.getAadharnumber());
//		copy.setBloodgroup(this.getBloodgroup());
//		copy.setCity(this.getCity());
//		copy.setCountry(this.getCountry());
//		copy.setCreationdate(this.getCreationdate());
//		copy.setDateofbirth(this.getDateofbirth());
//		copy.setEducation(this.getEducation());
//		copy.setEmailaddress(this.getEmailaddress());
//		copy.setEmergencycontactname(this.getEmergencycontactname());
//		copy.setEmergencycontactnumber(this.getEmergencycontactnumber());
//		copy.setEmergencycontactrelationship(this.getEmergencycontactrelationship());
//		copy.setFamilyhistory(this.getFamilyhistory());
//		copy.setFirstname(this.getFirstname());
//		copy.setGender(this.getGender());
//		copy.setHabbits(this.getHabbits());
//		copy.setInsuranceexpiration(this.getInsuranceexpiration());
//		copy.setInsurancenumber(this.getInsurancenumber());
//		copy.setLastname(this.getLastname());
//		copy.setLcality(this.getLcality());
//		copy.setMaritalstatus(this.getMaritalstatus());
//		copy.setMedicalhistory(this.getMedicalhistory());
//		copy.setMiddlename(this.getMiddlename());
//		copy.setModifiedby(this.getModifiedby());
//		copy.setModifieddate(this.getModifieddate());
//		copy.setOccupation(this.getOccupation());
//		copy.setPackageidFk(this.getPackageidFk());
//		copy.setPatientdisplayid(this.getPatientdisplayid());
//		copy.setPatientnote(this.getPatientnote());
//		copy.setPhonenumber(this.getPhonenumber());
//		copy.setPincode(this.getPincode());
//		copy.setPlaceofbirth(this.getPlaceofbirth());
//		copy.setReligion(this.getReligion());
//		copy.setSocialhistory(this.getSocialhistory());
//		copy.setState(this.getState());
//		copy.setStreet1(this.getStreet1());
//		copy.setStreet2(this.getStreet2());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("aadharnumber: " + this.getAadharnumber() + ", ");
//		sb.append("bloodgroup: " + this.getBloodgroup() + ", ");
//		sb.append("city: " + this.getCity() + ", ");
//		sb.append("country: " + this.getCountry() + ", ");
//		sb.append("creationdate: " + this.getCreationdate() + ", ");
//		sb.append("dateofbirth: " + this.getDateofbirth() + ", ");
//		sb.append("education: " + this.getEducation() + ", ");
//		sb.append("emailaddress: " + this.getEmailaddress() + ", ");
//		sb.append("emergencycontactname: " + this.getEmergencycontactname() + ", ");
//		sb.append("emergencycontactnumber: " + this.getEmergencycontactnumber() + ", ");
//		sb.append("emergencycontactrelationship: " + this.getEmergencycontactrelationship() + ", ");
//		sb.append("familyhistory: " + this.getFamilyhistory() + ", ");
//		sb.append("firstname: " + this.getFirstname() + ", ");
//		sb.append("gender: " + this.getGender() + ", ");
//		sb.append("habbits: " + this.getHabbits() + ", ");
//		sb.append("insuranceexpiration: " + this.getInsuranceexpiration() + ", ");
//		sb.append("insurancenumber: " + this.getInsurancenumber() + ", ");
//		sb.append("lastname: " + this.getLastname() + ", ");
//		sb.append("lcality: " + this.getLcality() + ", ");
//		sb.append("maritalstatus: " + this.getMaritalstatus() + ", ");
//		sb.append("medicalhistory: " + this.getMedicalhistory() + ", ");
//		sb.append("middlename: " + this.getMiddlename() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("modifieddate: " + this.getModifieddate() + ", ");
//		sb.append("occupation: " + this.getOccupation() + ", ");
//		sb.append("packageidFk: " + this.getPackageidFk() + ", ");
//		sb.append("patientdisplayid: " + this.getPatientdisplayid() + ", ");
//		sb.append("patientnote: " + this.getPatientnote() + ", ");
//		sb.append("phonenumber: " + this.getPhonenumber() + ", ");
//		sb.append("pincode: " + this.getPincode() + ", ");
//		sb.append("placeofbirth: " + this.getPlaceofbirth() + ", ");
//		sb.append("religion: " + this.getReligion() + ", ");
//		sb.append("socialhistory: " + this.getSocialhistory() + ", ");
//		sb.append("state: " + this.getState() + ", ");
//		sb.append("street1: " + this.getStreet1() + ", ");
//		sb.append("street2: " + this.getStreet2());
//		if (this.getClass().getSuperclass() != this.getClass()) {
//			sb.append("(super.toString=" + super.toString() + ")");
//		}
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdPatient that;
//		try {
//			that = (JdPatient) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		if (this.getClass().getSuperclass() != this.getClass()) {
//			result = super.equals(that);
//		}
//		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getAadharnumber() == null) && (that.getAadharnumber() == null)) || (getAadharnumber() != null && getAadharnumber().equals(that.getAadharnumber())));
//		result = result && (((getBloodgroup() == null) && (that.getBloodgroup() == null)) || (getBloodgroup() != null && getBloodgroup().equals(that.getBloodgroup())));
//		result = result && (((getCity() == null) && (that.getCity() == null)) || (getCity() != null && getCity().equals(that.getCity())));
//		result = result && (((getCountry() == null) && (that.getCountry() == null)) || (getCountry() != null && getCountry().equals(that.getCountry())));
//		result = result && (((getCreationdate() == null) && (that.getCreationdate() == null)) || (getCreationdate() != null && getCreationdate().equals(that.getCreationdate())));
//		result = result && (((getDateofbirth() == null) && (that.getDateofbirth() == null)) || (getDateofbirth() != null && getDateofbirth().equals(that.getDateofbirth())));
//		result = result && (((getEducation() == null) && (that.getEducation() == null)) || (getEducation() != null && getEducation().equals(that.getEducation())));
//		result = result && (((getEmailaddress() == null) && (that.getEmailaddress() == null)) || (getEmailaddress() != null && getEmailaddress().equals(that.getEmailaddress())));
//		result = result && (((getEmergencycontactname() == null) && (that.getEmergencycontactname() == null)) || (getEmergencycontactname() != null && getEmergencycontactname().equals(that.getEmergencycontactname())));
//		result = result && (((getEmergencycontactnumber() == null) && (that.getEmergencycontactnumber() == null)) || (getEmergencycontactnumber() != null && getEmergencycontactnumber().equals(that.getEmergencycontactnumber())));
//		result = result && (((getEmergencycontactrelationship() == null) && (that.getEmergencycontactrelationship() == null)) || (getEmergencycontactrelationship() != null && getEmergencycontactrelationship().equals(that.getEmergencycontactrelationship())));
//		result = result && (((getFamilyhistory() == null) && (that.getFamilyhistory() == null)) || (getFamilyhistory() != null && getFamilyhistory().equals(that.getFamilyhistory())));
//		result = result && (((getFirstname() == null) && (that.getFirstname() == null)) || (getFirstname() != null && getFirstname().equals(that.getFirstname())));
//		result = result && (((getGender() == null) && (that.getGender() == null)) || (getGender() != null && getGender().equals(that.getGender())));
//		result = result && (((getHabbits() == null) && (that.getHabbits() == null)) || (getHabbits() != null && getHabbits().equals(that.getHabbits())));
//		result = result && (((getInsuranceexpiration() == null) && (that.getInsuranceexpiration() == null)) || (getInsuranceexpiration() != null && getInsuranceexpiration().equals(that.getInsuranceexpiration())));
//		result = result && (((getInsurancenumber() == null) && (that.getInsurancenumber() == null)) || (getInsurancenumber() != null && getInsurancenumber().equals(that.getInsurancenumber())));
//		result = result && (((getLastname() == null) && (that.getLastname() == null)) || (getLastname() != null && getLastname().equals(that.getLastname())));
//		result = result && (((getLcality() == null) && (that.getLcality() == null)) || (getLcality() != null && getLcality().equals(that.getLcality())));
//		result = result && (((getMaritalstatus() == null) && (that.getMaritalstatus() == null)) || (getMaritalstatus() != null && getMaritalstatus().equals(that.getMaritalstatus())));
//		result = result && (((getMedicalhistory() == null) && (that.getMedicalhistory() == null)) || (getMedicalhistory() != null && getMedicalhistory().equals(that.getMedicalhistory())));
//		result = result && (((getMiddlename() == null) && (that.getMiddlename() == null)) || (getMiddlename() != null && getMiddlename().equals(that.getMiddlename())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getModifieddate() == null) && (that.getModifieddate() == null)) || (getModifieddate() != null && getModifieddate().equals(that.getModifieddate())));
//		result = result && (((getOccupation() == null) && (that.getOccupation() == null)) || (getOccupation() != null && getOccupation().equals(that.getOccupation())));
//		result = result && (((getPackageidFk() == null) && (that.getPackageidFk() == null)) || (getPackageidFk() != null && getPackageidFk().equals(that.getPackageidFk())));
//		result = result && (((getPatientdisplayid() == null) && (that.getPatientdisplayid() == null)) || (getPatientdisplayid() != null && getPatientdisplayid().equals(that.getPatientdisplayid())));
//		result = result && (((getPatientnote() == null) && (that.getPatientnote() == null)) || (getPatientnote() != null && getPatientnote().equals(that.getPatientnote())));
//		result = result && (((getPhonenumber() == null) && (that.getPhonenumber() == null)) || (getPhonenumber() != null && getPhonenumber().equals(that.getPhonenumber())));
//		result = result && (((getPincode() == null) && (that.getPincode() == null)) || (getPincode() != null && getPincode().equals(that.getPincode())));
//		result = result && (((getPlaceofbirth() == null) && (that.getPlaceofbirth() == null)) || (getPlaceofbirth() != null && getPlaceofbirth().equals(that.getPlaceofbirth())));
//		result = result && (((getReligion() == null) && (that.getReligion() == null)) || (getReligion() != null && getReligion().equals(that.getReligion())));
//		result = result && (((getSocialhistory() == null) && (that.getSocialhistory() == null)) || (getSocialhistory() != null && getSocialhistory().equals(that.getSocialhistory())));
//		result = result && (((getState() == null) && (that.getState() == null)) || (getState() != null && getState().equals(that.getState())));
//		result = result && (((getStreet1() == null) && (that.getStreet1() == null)) || (getStreet1() != null && getStreet1().equals(that.getStreet1())));
//		result = result && (((getStreet2() == null) && (that.getStreet2() == null)) || (getStreet2() != null && getStreet2().equals(that.getStreet2())));
//		return result;
//	}
//
//
//
//
//}
