//package com.techstomach.ehs.core;
//
//import java.io.Serializable;
//import java.util.Collections;
//import java.util.Date;
//import java.util.Map;
//import java.util.WeakHashMap;
//import javax.persistence.Basic;
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_patient_medical_chart.
// * @author autogenerated
// */
//
//@Entity
//@Table(name = "jd_patient_medical_chart", catalog = "jdehs_dev")
//public class JdPatientMedicalChart implements Cloneable, Serializable{
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033255L;
//
//	/** Use a WeakHashMap so entries will be garbage collected once all entities
//		referring to a saved hash are garbage collected themselves. */
//	private static final Map<Serializable, Serializable> SAVED_HASHES =
//		Collections.synchronizedMap(new WeakHashMap<Serializable, Serializable>());
//
//	/** hashCode temporary storage. */
//	private volatile Serializable hashCode;
//
//
//	/** Field mapping. */
//	private String chartcategory;
//	/** Field mapping. */
//	private String chartitem;
//	/** Field mapping. */
//	private String comments;
//	/** Field mapping. */
//	private Date creationdate;
//	/** Field mapping. */
//	private Integer isvalid;
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Date modifieddate;
//	/** Field mapping. */
//	private JdUser useridFk;
//
//
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Transient
//	public Class<?> getClassType() {
//		return JdPatientMedicalChart.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: chartcategory.
//	 * @return A String object (this.chartcategory)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getChartcategory() {
//		return this.chartcategory;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: chartcategory.
//	 * @param chartcategory the chartcategory value you wish to set
//	 */
//	public void setChartcategory(final String chartcategory) {
//		this.chartcategory = chartcategory;
//	}
//
//    /**
//     * Return the value associated with the column: chartitem.
//	 * @return A String object (this.chartitem)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getChartitem() {
//		return this.chartitem;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: chartitem.
//	 * @param chartitem the chartitem value you wish to set
//	 */
//	public void setChartitem(final String chartitem) {
//		this.chartitem = chartitem;
//	}
//
//    /**
//     * Return the value associated with the column: comments.
//	 * @return A String object (this.comments)
//	 */
//	@Basic( optional = true )
//	@Column( length = 715827882  )
//	public String getComments() {
//		return this.comments;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: comments.
//	 * @param comments the comments value you wish to set
//	 */
//	public void setComments(final String comments) {
//		this.comments = comments;
//	}
//
//    /**
//     * Return the value associated with the column: creationdate.
//	 * @return A Date object (this.creationdate)
//	 */
//	public Date getCreationdate() {
//		return this.creationdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: creationdate.
//	 * @param creationdate the creationdate value you wish to set
//	 */
//	public void setCreationdate(final Date creationdate) {
//		this.creationdate = creationdate;
//	}
//
//    /**
//     * Return the value associated with the column: isvalid.
//	 * @return A Integer object (this.isvalid)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false  )
//	public Integer getIsvalid() {
//		return this.isvalid;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: isvalid.
//	 * @param isvalid the isvalid value you wish to set
//	 */
//	public void setIsvalid(final Integer isvalid) {
//		this.isvalid = isvalid;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: modifieddate.
//	 * @return A Date object (this.modifieddate)
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifieddate.
//	 * @param modifieddate the modifieddate value you wish to set
//	 */
//	public void setModifieddate(final Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//    /**
//     * Return the value associated with the column: useridFk.
//	 * @return A JdUser object (this.useridFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "userId_fk", nullable = false )
//	public JdUser getUseridFk() {
//		return this.useridFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: useridFk.
//	 * @param useridFk the useridFk value you wish to set
//	 */
//	public void setUseridFk(final JdUser useridFk) {
//		this.useridFk = useridFk;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdPatientMedicalChart clone() throws CloneNotSupportedException {
//
//        final JdPatientMedicalChart copy = (JdPatientMedicalChart)super.clone();
//
//		copy.setChartcategory(this.getChartcategory());
//		copy.setChartitem(this.getChartitem());
//		copy.setComments(this.getComments());
//		copy.setCreationdate(this.getCreationdate());
//		copy.setIsvalid(this.getIsvalid());
//		copy.setModifiedby(this.getModifiedby());
//		copy.setModifieddate(this.getModifieddate());
//		copy.setUseridFk(this.getUseridFk());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("chartcategory: " + this.getChartcategory() + ", ");
//		sb.append("chartitem: " + this.getChartitem() + ", ");
//		sb.append("comments: " + this.getComments() + ", ");
//		sb.append("creationdate: " + this.getCreationdate() + ", ");
//		sb.append("isvalid: " + this.getIsvalid() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("modifieddate: " + this.getModifieddate() + ", ");
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdPatientMedicalChart that;
//		try {
//			that = (JdPatientMedicalChart) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		result = result && (((getChartcategory() == null) && (that.getChartcategory() == null)) || (getChartcategory() != null && getChartcategory().equals(that.getChartcategory())));
//		result = result && (((getChartitem() == null) && (that.getChartitem() == null)) || (getChartitem() != null && getChartitem().equals(that.getChartitem())));
//		result = result && (((getComments() == null) && (that.getComments() == null)) || (getComments() != null && getComments().equals(that.getComments())));
//		result = result && (((getCreationdate() == null) && (that.getCreationdate() == null)) || (getCreationdate() != null && getCreationdate().equals(that.getCreationdate())));
//		result = result && (((getIsvalid() == null) && (that.getIsvalid() == null)) || (getIsvalid() != null && getIsvalid().equals(that.getIsvalid())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getModifieddate() == null) && (that.getModifieddate() == null)) || (getModifieddate() != null && getModifieddate().equals(that.getModifieddate())));
//		result = result && (((getUseridFk() == null) && (that.getUseridFk() == null)) || (getUseridFk() != null && getUseridFk().getId().equals(that.getUseridFk().getId())));
//		return result;
//	}
//
//}
