server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  rootPath: /api/

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: jd_admin
    # the password
    password: jd_admin
    # the JDBC URL; the database is called hello_world
    url: jdbc:mysql://localhost:3306/jdehs_dev
    # the SQL query to run when validating a connection's liveness
    validationQuery: "/* MyService Health Check */ SELECT 1"

    properties:
        hibernate.show_sql: true
        hibernate.generate_statistics: false
        hibernate.hbm2ddl.auto: validate # validates schema when service is started

swagger:
  resourcePackage: com.techstomach.ehs.resources