//package com.techstomach.ehs.core;
//
//import java.io.Serializable;
//import java.util.Collections;
//import java.util.Date;
//import java.util.Map;
//import java.util.WeakHashMap;
//import javax.persistence.Basic;
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//import org.hibernate.proxy.HibernateProxy;
//
//
///**
// * Object mapping for hibernate-handled table: jd_diagnostic_chart.
// * @author autogenerated
// */
//
//@Entity
//@Table(name = "jd_diagnostic_chart", catalog = "jdehs_dev")
//public class JdDiagnosticChart implements Cloneable, Serializable{
//
//	/** Serial Version UID. */
//	private static final long serialVersionUID = -559033260L;
//
//	/** Use a WeakHashMap so entries will be garbage collected once all entities
//		referring to a saved hash are garbage collected themselves. */
//	private static final Map<Serializable, Long> SAVED_HASHES =
//		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
//
//	/** hashCode temporary storage. */
//	private volatile Long hashCode;
//
//
//	/** Field mapping. */
//	private JdAppointment appointmentidFk;
//	/** Field mapping. */
//	private JdClinic clinicidFk;
//	/** Field mapping. */
//	private String comments;
//	/** Field mapping. */
//	private Date creationdate;
//	/** Field mapping. */
//	private Long id = 0L; // init for hibernate bug workaround
//	/** Field mapping. */
//	private String interactiontype;
//	/** Field mapping. */
//	private String modifiedby;
//	/** Field mapping. */
//	private Date modifieddate;
//	/** Field mapping. */
//	private JdUser useridFk;
//	/** Field mapping. */
//	private Date validfrom;
//	/** Field mapping. */
//	private Date validto;
//	/**
//	 * Default constructor, mainly for hibernate use.
//	 */
//	public JdDiagnosticChart() {
//		// Default constructor
//	}
//
//	/** Constructor taking a given ID.
//	 * @param id to set
//	 */
//	public JdDiagnosticChart(Long id) {
//		this.id = id;
//	}
//
//	/** Constructor taking a given ID.
//	 * @param appointmentidFk JdAppointment object;
//	 * @param clinicidFk JdClinic object;
//	 * @param id Long object;
//	 * @param interactiontype String object;
//	 * @param modifiedby String object;
//	 * @param useridFk JdUser object;
//	 */
//	public JdDiagnosticChart(JdAppointment appointmentidFk, JdClinic clinicidFk, Long id,
//			String interactiontype, String modifiedby, JdUser useridFk) {
//
//		this.appointmentidFk = appointmentidFk;
//		this.clinicidFk = clinicidFk;
//		this.id = id;
//		this.interactiontype = interactiontype;
//		this.modifiedby = modifiedby;
//		this.useridFk = useridFk;
//	}
//
//
//
//
//
//	/** Return the type of this class. Useful for when dealing with proxies.
//	* @return Defining class.
//	*/
//	@Transient
//	public Class<?> getClassType() {
//		return JdDiagnosticChart.class;
//	}
//
//
//    /**
//     * Return the value associated with the column: appointmentidFk.
//	 * @return A JdAppointment object (this.appointmentidFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "appointmentId_fk" )
//	public JdAppointment getAppointmentidFk() {
//		return this.appointmentidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: appointmentidFk.
//	 * @param appointmentidFk the appointmentidFk value you wish to set
//	 */
//	public void setAppointmentidFk(final JdAppointment appointmentidFk) {
//		this.appointmentidFk = appointmentidFk;
//	}
//
//    /**
//     * Return the value associated with the column: clinicidFk.
//	 * @return A JdClinic object (this.clinicidFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "clinicId_fk" )
//	public JdClinic getClinicidFk() {
//		return this.clinicidFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: clinicidFk.
//	 * @param clinicidFk the clinicidFk value you wish to set
//	 */
//	public void setClinicidFk(final JdClinic clinicidFk) {
//		this.clinicidFk = clinicidFk;
//	}
//
//    /**
//     * Return the value associated with the column: comments.
//	 * @return A String object (this.comments)
//	 */
//	@Basic( optional = true )
//	@Column( length = 715827882  )
//	public String getComments() {
//		return this.comments;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: comments.
//	 * @param comments the comments value you wish to set
//	 */
//	public void setComments(final String comments) {
//		this.comments = comments;
//	}
//
//    /**
//     * Return the value associated with the column: creationdate.
//	 * @return A Date object (this.creationdate)
//	 */
//	public Date getCreationdate() {
//		return this.creationdate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: creationdate.
//	 * @param creationdate the creationdate value you wish to set
//	 */
//	public void setCreationdate(final Date creationdate) {
//		this.creationdate = creationdate;
//	}
//
//    /**
//     * Return the value associated with the column: id.
//	 * @return A Long object (this.id)
//	 */
//    @Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Basic( optional = false )
//	@Column( name = "procedureid"  )
//	public Long getId() {
//		return this.id;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: id.
//	 * @param id the id value you wish to set
//	 */
//	public void setId(final Long id) {
//		// If we've just been persisted and hashCode has been
//		// returned then make sure other entities with this
//		// ID return the already returned hash code
//		if ( (this.id == null || this.id == 0L) &&
//				(id != null) &&
//				(this.hashCode != null) ) {
//		SAVED_HASHES.put( id, this.hashCode );
//		}
//		this.id = id;
//	}
//
//    /**
//     * Return the value associated with the column: interactiontype.
//	 * @return A String object (this.interactiontype)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getInteractiontype() {
//		return this.interactiontype;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: interactiontype.
//	 * @param interactiontype the interactiontype value you wish to set
//	 */
//	public void setInteractiontype(final String interactiontype) {
//		this.interactiontype = interactiontype;
//	}
//
//    /**
//     * Return the value associated with the column: modifiedby.
//	 * @return A String object (this.modifiedby)
//	 */
//	@Basic( optional = false )
//	@Column( nullable = false, length = 255  )
//	public String getModifiedby() {
//		return this.modifiedby;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifiedby.
//	 * @param modifiedby the modifiedby value you wish to set
//	 */
//	public void setModifiedby(final String modifiedby) {
//		this.modifiedby = modifiedby;
//	}
//
//    /**
//     * Return the value associated with the column: modifieddate.
//	 * @return A Date object (this.modifieddate)
//	 */
//	public Date getModifieddate() {
//		return this.modifieddate;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: modifieddate.
//	 * @param modifieddate the modifieddate value you wish to set
//	 */
//	public void setModifieddate(final Date modifieddate) {
//		this.modifieddate = modifieddate;
//	}
//
//    /**
//     * Return the value associated with the column: useridFk.
//	 * @return A JdUser object (this.useridFk)
//	 */
//	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
//	@Basic( optional = false )
//	@JoinColumn(name = "userId_fk" )
//	public JdUser getUseridFk() {
//		return this.useridFk;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: useridFk.
//	 * @param useridFk the useridFk value you wish to set
//	 */
//	public void setUseridFk(final JdUser useridFk) {
//		this.useridFk = useridFk;
//	}
//
//    /**
//     * Return the value associated with the column: validfrom.
//	 * @return A Date object (this.validfrom)
//	 */
//	public Date getValidfrom() {
//		return this.validfrom;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: validfrom.
//	 * @param validfrom the validfrom value you wish to set
//	 */
//	public void setValidfrom(final Date validfrom) {
//		this.validfrom = validfrom;
//	}
//
//    /**
//     * Return the value associated with the column: validto.
//	 * @return A Date object (this.validto)
//	 */
//	public Date getValidto() {
//		return this.validto;
//
//	}
//
//
//
//    /**
//     * Set the value related to the column: validto.
//	 * @param validto the validto value you wish to set
//	 */
//	public void setValidto(final Date validto) {
//		this.validto = validto;
//	}
//
//
//   /**
//    * Deep copy.
//	* @return cloned object
//	* @throws CloneNotSupportedException on error
//    */
//    @Override
//    public JdDiagnosticChart clone() throws CloneNotSupportedException {
//
//        final JdDiagnosticChart copy = (JdDiagnosticChart)super.clone();
//
//		copy.setAppointmentidFk(this.getAppointmentidFk());
//		copy.setClinicidFk(this.getClinicidFk());
//		copy.setComments(this.getComments());
//		copy.setCreationdate(this.getCreationdate());
//		copy.setId(this.getId());
//		copy.setInteractiontype(this.getInteractiontype());
//		copy.setModifiedby(this.getModifiedby());
//		copy.setModifieddate(this.getModifieddate());
//		copy.setUseridFk(this.getUseridFk());
//		copy.setValidfrom(this.getValidfrom());
//		copy.setValidto(this.getValidto());
//		return copy;
//	}
//
//
//
//	/** Provides toString implementation.
//	 * @see Object#toString()
//	 * @return String representation of this class.
//	 */
//	@Override
//	public String toString() {
//		StringBuffer sb = new StringBuffer();
//
//		sb.append("comments: " + this.getComments() + ", ");
//		sb.append("creationdate: " + this.getCreationdate() + ", ");
//		sb.append("id: " + this.getId() + ", ");
//		sb.append("interactiontype: " + this.getInteractiontype() + ", ");
//		sb.append("modifiedby: " + this.getModifiedby() + ", ");
//		sb.append("modifieddate: " + this.getModifieddate() + ", ");
//		sb.append("validfrom: " + this.getValidfrom() + ", ");
//		sb.append("validto: " + this.getValidto());
//		return sb.toString();
//	}
//
//
//	/** Equals implementation.
//	 * @see Object#equals(Object)
//	 * @param aThat Object to compare with
//	 * @return true/false
//	 */
//	@Override
//	public boolean equals(final Object aThat) {
//		Object proxyThat = aThat;
//
//		if ( this == aThat ) {
//			 return true;
//		}
//
//
//		if (aThat instanceof HibernateProxy) {
// 			// narrow down the proxy to the class we are dealing with.
// 			try {
//				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation();
//			} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		   	}
//		}
//		if (aThat == null)  {
//			 return false;
//		}
//
//		final JdDiagnosticChart that;
//		try {
//			that = (JdDiagnosticChart) proxyThat;
//			if ( !(that.getClassType().equals(this.getClassType()))){
//				return false;
//			}
//		} catch (org.hibernate.ObjectNotFoundException e) {
//				return false;
//		} catch (ClassCastException e) {
//				return false;
//		}
//
//
//		boolean result = true;
//		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
//		result = result && (((getAppointmentidFk() == null) && (that.getAppointmentidFk() == null)) || (getAppointmentidFk() != null && getAppointmentidFk().getId().equals(that.getAppointmentidFk().getId())));
//		result = result && (((getClinicidFk() == null) && (that.getClinicidFk() == null)) || (getClinicidFk() != null && getClinicidFk().getId().equals(that.getClinicidFk().getId())));
//		result = result && (((getComments() == null) && (that.getComments() == null)) || (getComments() != null && getComments().equals(that.getComments())));
//		result = result && (((getCreationdate() == null) && (that.getCreationdate() == null)) || (getCreationdate() != null && getCreationdate().equals(that.getCreationdate())));
//		result = result && (((getInteractiontype() == null) && (that.getInteractiontype() == null)) || (getInteractiontype() != null && getInteractiontype().equals(that.getInteractiontype())));
//		result = result && (((getModifiedby() == null) && (that.getModifiedby() == null)) || (getModifiedby() != null && getModifiedby().equals(that.getModifiedby())));
//		result = result && (((getModifieddate() == null) && (that.getModifieddate() == null)) || (getModifieddate() != null && getModifieddate().equals(that.getModifieddate())));
//		result = result && (((getUseridFk() == null) && (that.getUseridFk() == null)) || (getUseridFk() != null && getUseridFk().getId().equals(that.getUseridFk().getId())));
//		result = result && (((getValidfrom() == null) && (that.getValidfrom() == null)) || (getValidfrom() != null && getValidfrom().equals(that.getValidfrom())));
//		result = result && (((getValidto() == null) && (that.getValidto() == null)) || (getValidto() != null && getValidto().equals(that.getValidto())));
//		return result;
//	}
//
//	/** Calculate the hashcode.
//	 * @see Object#hashCode()
//	 * @return a calculated number
//	 */
//	@Override
//	public int hashCode() {
//		if ( this.hashCode == null ) {
//			synchronized ( this ) {
//				if ( this.hashCode == null ) {
//					Long newHashCode = null;
//
//					if ( getId() != null ) {
//					newHashCode = SAVED_HASHES.get( getId() );
//					}
//
//					if ( newHashCode == null ) {
//						if ( getId() != null && getId() != 0L) {
//							newHashCode = getId();
//						} else {
//							newHashCode = (long) super.hashCode();
//
//						}
//					}
//
//					this.hashCode = newHashCode;
//				}
//			}
//		}
//		return (int) (this.hashCode & 0xffffff);
//	}
//
//
//
//}
